using System.Collections.Generic;
using System.Text.Json.Serialization;
using Nexus.Service.Activity;
using Nexus.Service.Helper;
using Nexus.Service.Models;
using Nexus.Service.Models.Activity;
using Nexus.Service.Models.Benchmarks;
using Nexus.Service.Models.Cooling;
using Nexus.Service.Models.Devices;
using Nexus.Service.Models.Discord;
using Nexus.Service.Models.Lifecycle;
using Nexus.Service.Models.Lighting;
using Nexus.Service.Models.Obs;
using Nexus.Service.Models.Peripherals;
using Nexus.Service.Models.Peripherals.Keeb;
using Nexus.Service.Models.Peripherals.Y70;
using Nexus.Service.Models.Sensors;
using Nexus.Service.Models.Steam;
using Nexus.Service.Models.Widgets;
using Nexus.Service.Platform;
using Nexus.Service.Routes;

namespace Nexus.Service.Serialization;

// Ping + Auth
[JsonSerializable(typeof(ApiResponse))]
[JsonSerializable(typeof(PingResponse))]
[JsonSerializable(typeof(PairResponse))]

// System / sensors
[JsonSerializable(typeof(PerformanceSnapshot))]
[JsonSerializable(typeof(HardwareSensor))]
[JsonSerializable(typeof(List<HardwareSensor>))]
[JsonSerializable(typeof(IReadOnlyList<HardwareSensor>))]
[JsonSerializable(typeof(HardwareComponent))]
[JsonSerializable(typeof(List<HardwareComponent>))]
[JsonSerializable(typeof(StorageComponent))]
[JsonSerializable(typeof(Dictionary<string, StorageComponent>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, StorageComponent>))]
[JsonSerializable(typeof(StorageDriveInfo))]
[JsonSerializable(typeof(SensorExtras))]
[JsonSerializable(typeof(GetModelResponse))]
[JsonSerializable(typeof(GetGpuModelsResponse))]
[JsonSerializable(typeof(CpuHealthResponse))]
[JsonSerializable(typeof(ProcessElevationResponse))]
[JsonSerializable(typeof(ProcessElevationRelaunchResponse))]
[JsonSerializable(typeof(GetStoragePartitionsResponse))]
[JsonSerializable(typeof(GetDriveStorageResponse))]
[JsonSerializable(typeof(SystemSpecsResponse))]
[JsonSerializable(typeof(GetPollingRateResponse))]

// Cooling
[JsonSerializable(typeof(CoolingComponent))]
[JsonSerializable(typeof(GetAllCoolingResponse))]
[JsonSerializable(typeof(SetCurvesBody))]
[JsonSerializable(typeof(GetCurvesResponse))]
[JsonSerializable(typeof(CoolingWarning))]
[JsonSerializable(typeof(List<CoolingWarning>))]
[JsonSerializable(typeof(GetCoolingWarningsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cooling.GraphPoint), TypeInfoPropertyName = "CoolingGraphPoint")]
[JsonSerializable(typeof(List<Nexus.Service.Models.Cooling.GraphPoint>), TypeInfoPropertyName = "CoolingListGraphPoint")]

// NP50 device state surface
[JsonSerializable(typeof(Nexus.Service.Routes.Np50StateResponse))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50State))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50HubInfo))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50Port))]
[JsonSerializable(typeof(List<Nexus.Service.Peripherals.Hyte.Np50.Np50Port>))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50FanDevice))]
[JsonSerializable(typeof(List<Nexus.Service.Peripherals.Hyte.Np50.Np50FanDevice>))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50WarningDetail))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50PortWarning))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50LightingRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50LedColor))]
[JsonSerializable(typeof(List<Nexus.Service.Routes.Np50LedColor>))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareDefaultsResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareDefaultsRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareAnimationResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareAnimationRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50CoolingModeRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.MiniHubCoolingModeRequest))]

// SmartHub device state surface
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubFanResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubFanResponse[]))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubFwSettingResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubFwSettingRequest))]

// Fan control
[JsonSerializable(typeof(FanChannel))]
[JsonSerializable(typeof(List<FanChannel>))]
[JsonSerializable(typeof(TemperatureSource))]
[JsonSerializable(typeof(List<TemperatureSource>))]
[JsonSerializable(typeof(GetFanChannelsResponse))]
[JsonSerializable(typeof(GetTemperatureSourcesResponse))]
[JsonSerializable(typeof(SetFanSpeedBody))]
[JsonSerializable(typeof(SetFanNameBody))]
[JsonSerializable(typeof(SetFanSpeedResponse))]
[JsonSerializable(typeof(CurveOutputState))]
[JsonSerializable(typeof(CurveCalculation))]
[JsonSerializable(typeof(CurveCalculationsFrame))]
[JsonSerializable(typeof(FanProfile))]
[JsonSerializable(typeof(List<FanProfile>))]
[JsonSerializable(typeof(GetProfilesResponse))]
[JsonSerializable(typeof(ApplyProfileResponse))]
[JsonSerializable(typeof(StartupModeBody))]
[JsonSerializable(typeof(StartupModeDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.TelemetryConsentBody))]
[JsonSerializable(typeof(Nexus.Service.Routes.TelemetryConsentDto))]
[JsonSerializable(typeof(FanCalibration))]
[JsonSerializable(typeof(List<FanCalibration>))]
[JsonSerializable(typeof(FanCalibrationPoint))]
[JsonSerializable(typeof(List<FanCalibrationPoint>))]
[JsonSerializable(typeof(FanCalibrationProgress))]
[JsonSerializable(typeof(StartCalibrationBody))]
[JsonSerializable(typeof(CoolingStatusResponse))]
[JsonSerializable(typeof(LightingStatusResponse))]
[JsonSerializable(typeof(List<float>))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.MusicReactiveBody))]
[JsonSerializable(typeof(CalibrationStartResponse))]
[JsonSerializable(typeof(GetCalibrationsResponse))]

// Profiles
[JsonSerializable(typeof(Nexus.Service.Persistence.ProfileManifest))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ProfileEntry))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.ProfileEntry>))]
[JsonSerializable(typeof(Nexus.Service.Persistence.GraphPoint), TypeInfoPropertyName = "PersistenceGraphPoint")]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.GraphPoint>), TypeInfoPropertyName = "PersistenceListGraphPoint")]
[JsonSerializable(typeof(Nexus.Service.Persistence.UiSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.UiSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ThemeSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.MonitoringSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.OverlaySettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelLayoutsDefaults))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelLayoutDefault))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelLayoutWidget))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.PanelLayoutWidget>))]
[JsonSerializable(typeof(Nexus.Service.Persistence.Preferences))]
[JsonSerializable(typeof(Nexus.Service.Persistence.CoolingPrefs))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PreferencesPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ThemeSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.OverlaySettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.MonitoringSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.CoolingPrefsPatch))]

// Panel widget engine - per-device records, layouts, control-state push frames.
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelLayoutDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPageDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelWidgetDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.PanelPageDto>))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.PanelWidgetDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceRecord))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceCapabilities))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDevicePatch))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceCreateBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceListResponse))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.PanelDeviceRecord>))]
[JsonSerializable(typeof(Dictionary<string, Nexus.Service.Models.Panel.PanelDeviceRecord>))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PrefsChangedFrame))]

// Desktop widgets - floating panel widgets on the Windows desktop.
[JsonSerializable(typeof(Nexus.Service.Models.Panel.OverlayWidgetDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.OverlayWidgetCreateBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.OverlayWidgetPatch))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.OverlayWidgetDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.LightingChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.CoolingChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.VolumeChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PairQrRefreshFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.SystemAccentFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.CoolingWarningsChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.DevicesChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairQrResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneClaimBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneClaimResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneServiceInfoResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneSessionNameBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelHostNameBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelHostNameResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneSessionsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneSessionDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.PanelPhoneSessionDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelStatusResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RemoteControlStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RemoteControlToggleRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayToggleRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayHostHello))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayClaimRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayClaimResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayHttpRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayHttpResponse))]
[JsonSerializable(typeof(Nexus.Service.Relay.RelayDirectoryResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PairBroadcastStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PairBroadcastSetRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PairWifiInitiateRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeStartResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeSubmitBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeSubmitResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeConfirmBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeConfirmResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeHostDecisionBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeHostDecisionResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeRequestFrame))]

// Displays (system monitors: brightness + DDC/CI VCP)
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Displays.DisplayDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayCapabilitiesDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBrightnessControlDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBrightnessWritePolicy))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBrightnessDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBrightnessParams))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayVcpDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayVcpParams))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayListResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.RawDisplayInfo))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Displays.RawDisplayInfo>))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBoundsDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplaySizeDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayTopologyEntryDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayTopologyResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplaysChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.PanelPromoteBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayAssignmentDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayAssignmentsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayRotationBody))]

[JsonSerializable(typeof(Nexus.Service.Models.Profiles.ListProfilesResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.ProfileResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.SwitchProfileResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.CreateProfileBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.RenameProfileBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.ProfileExport))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.SharingResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.SetPrimaryBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.SetCategorySharedBody))]

// Media library
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaItem))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Media.MediaItem>))]
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaLibraryResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaImportResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Transfer.TransferItemsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Transfer.TransferClipboardBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Transfer.TransferReceivedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaPlayResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaCurrentResponse))]

// Gallery
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GallerySource))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Gallery.GallerySource>))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GallerySourcesFile))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GallerySourcesResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.AddGallerySourceBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GallerySourceMutationResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryItem))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Gallery.GalleryItem>))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryItemsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryPickBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryPickResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryExcludeBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.GalleryChangedFrame))]

// Lighting
[JsonSerializable(typeof(AudioStateSnapshot))]
[JsonSerializable(typeof(ShaderSourceResponse))]
[JsonSerializable(typeof(CurrentSyncResponse))]
[JsonSerializable(typeof(BrightnessScale))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.GlobalBrightnessBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.RenderGpuBody))]
[JsonSerializable(typeof(SpeedScale))]
[JsonSerializable(typeof(AnimateHeadlessStart))]
[JsonSerializable(typeof(SetAnimateTemplatesBody))]
[JsonSerializable(typeof(ShaderParam))]
[JsonSerializable(typeof(List<ShaderParam>))]
[JsonSerializable(typeof(Nexus.Service.Persistence.AnimateSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.AnimateEffectState))]
[JsonSerializable(typeof(Nexus.Service.Persistence.AnimateEffectTemplates))]
[JsonSerializable(typeof(Nexus.Service.Persistence.StaticColorSettings))]
[JsonSerializable(typeof(Dictionary<string, Nexus.Service.Persistence.AnimateEffectState>))]
[JsonSerializable(typeof(Dictionary<string, Nexus.Service.Persistence.AnimateEffectTemplates>))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.AnimateEffectState>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, float>>))]
[JsonSerializable(typeof(MusicHeadlessStart))]
[JsonSerializable(typeof(ScreenHeadlessStart))]
[JsonSerializable(typeof(ScreenSyncOptions))]
[JsonSerializable(typeof(ScreenSyncMonitor))]
[JsonSerializable(typeof(List<ScreenSyncMonitor>))]
[JsonSerializable(typeof(GifHeadlessStart))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.PostProcessBody))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PostProcessSettings))]

// OBS
[JsonSerializable(typeof(ObsConfigResponse))]
[JsonSerializable(typeof(ObsConfigBody))]
[JsonSerializable(typeof(ObsStatusResponse))]
[JsonSerializable(typeof(ObsScene))]
[JsonSerializable(typeof(List<ObsScene>))]
[JsonSerializable(typeof(ObsSetSceneBody))]

// Steam
[JsonSerializable(typeof(SteamConfigResponse))]
[JsonSerializable(typeof(SteamConfigBody))]
[JsonSerializable(typeof(SteamStatusResponse))]
[JsonSerializable(typeof(SteamProfileResponse))]
[JsonSerializable(typeof(SteamPlayerSummary))]
[JsonSerializable(typeof(SteamRecentGame))]
[JsonSerializable(typeof(List<SteamRecentGame>))]
[JsonSerializable(typeof(SteamOwnedGame))]
[JsonSerializable(typeof(List<SteamOwnedGame>))]
[JsonSerializable(typeof(SteamFriendSummary))]
[JsonSerializable(typeof(List<SteamFriendSummary>))]
[JsonSerializable(typeof(SteamAchievement))]
[JsonSerializable(typeof(List<SteamAchievement>))]
[JsonSerializable(typeof(SteamCurrentPlayers))]
[JsonSerializable(typeof(SteamNewsItem))]
[JsonSerializable(typeof(List<SteamNewsItem>))]
[JsonSerializable(typeof(SteamGlobalAchievement))]
[JsonSerializable(typeof(List<SteamGlobalAchievement>))]
[JsonSerializable(typeof(SteamUserStat))]
[JsonSerializable(typeof(List<SteamUserStat>))]
[JsonSerializable(typeof(SteamAppDetails))]

// Discord
[JsonSerializable(typeof(DiscordConfigResponse))]
[JsonSerializable(typeof(DiscordConfigBody))]
[JsonSerializable(typeof(DiscordStatusResponse))]
[JsonSerializable(typeof(DiscordUser))]
[JsonSerializable(typeof(DiscordGuild))]
[JsonSerializable(typeof(List<DiscordGuild>))]
[JsonSerializable(typeof(DiscordVoiceState))]
[JsonSerializable(typeof(DiscordVoiceParticipant))]
[JsonSerializable(typeof(List<DiscordVoiceParticipant>))]
[JsonSerializable(typeof(DiscordNotification))]
[JsonSerializable(typeof(List<DiscordNotification>))]
[JsonSerializable(typeof(DiscordOpenBody))]
[JsonSerializable(typeof(DiscordVoiceToggleBody))]

// Devices
[JsonSerializable(typeof(Nexus.Service.Persistence.DeviceLayout))]
[JsonSerializable(typeof(SaveDeviceLayoutBody))]
[JsonSerializable(typeof(DeviceListItem))]
[JsonSerializable(typeof(List<DeviceListItem>))]
[JsonSerializable(typeof(UsbDeviceDetail))]
[JsonSerializable(typeof(List<UsbDeviceDetail>))]
[JsonSerializable(typeof(FirmwareStatusItem))]
[JsonSerializable(typeof(List<FirmwareStatusItem>))]
[JsonSerializable(typeof(FlashableImage))]
[JsonSerializable(typeof(List<FlashableImage>))]
[JsonSerializable(typeof(FlashRequest))]
[JsonSerializable(typeof(FlashStatusDto))]
[JsonSerializable(typeof(FlashStartResponse))]

// Peripherals (third-party mice/keyboards/headsets with protocol support)
[JsonSerializable(typeof(PeripheralDto))]
[JsonSerializable(typeof(List<PeripheralDto>))]
[JsonSerializable(typeof(GetPeripheralsResponse))]
[JsonSerializable(typeof(SupportedDeviceDto))]
[JsonSerializable(typeof(List<SupportedDeviceDto>))]
[JsonSerializable(typeof(GetSupportedDevicesResponse))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.OpenRgbSupportedDevicesFile))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.OpenRgbSupportedDeviceEntry))]
[JsonSerializable(typeof(List<Nexus.Service.Peripherals.OpenRgbSupportedDeviceEntry>))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Protocols.Razer.RazerMouseSpec))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Protocols.Razer.RazerMouseSpecEntry))]
[JsonSerializable(typeof(List<Nexus.Service.Peripherals.Protocols.Razer.RazerMouseSpecEntry>))]
[JsonSerializable(typeof(DpiState))]
[JsonSerializable(typeof(PollingState))]
[JsonSerializable(typeof(BatteryState))]
[JsonSerializable(typeof(SleepState))]
[JsonSerializable(typeof(ToggleState))]
[JsonSerializable(typeof(SetDpiBody))]
[JsonSerializable(typeof(SetPollingBody))]
[JsonSerializable(typeof(SetSleepBody))]
[JsonSerializable(typeof(SetToggleBody))]
[JsonSerializable(typeof(IsDeviceConnectedResponse))]
[JsonSerializable(typeof(FirmwareVersionResponse))]
[JsonSerializable(typeof(GetCnvsSettingsResponse))]
[JsonSerializable(typeof(SetCnvsSettingsBody))]
[JsonSerializable(typeof(UpdateBody))]
[JsonSerializable(typeof(CheckForUpdateResponse))]
[JsonSerializable(typeof(UpdateResponse))]
[JsonSerializable(typeof(GetMotherboardLEDsResponse))]
[JsonSerializable(typeof(SetMotherboardLEDsBody))]
[JsonSerializable(typeof(CheckFirmwareFunctionBody))]
[JsonSerializable(typeof(CheckFirmwareFunctionResponse))]
[JsonSerializable(typeof(GetLightingDevicesResponse))]
[JsonSerializable(typeof(SetDisabledLedsBody))]
[JsonSerializable(typeof(SetLightingDevicePowerBody))]
[JsonSerializable(typeof(SetLightingDeviceBrightness))]
[JsonSerializable(typeof(SetLightingDeviceHue))]
[JsonSerializable(typeof(SetLightingDeviceSaturation))]
[JsonSerializable(typeof(SetLightingDeviceColor))]
[JsonSerializable(typeof(SetZoneLedCountBody))]
[JsonSerializable(typeof(IdentifyLightingDeviceBody))]
[JsonSerializable(typeof(LedMapResponse))]
[JsonSerializable(typeof(LedMapEntry))]
[JsonSerializable(typeof(List<LedMapEntry>))]
[JsonSerializable(typeof(SaveLedMapBody))]
[JsonSerializable(typeof(Nexus.Service.Persistence.LedPositionOverride))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.LedPositionOverride>))]
[JsonSerializable(typeof(LedHighlightBody))]
[JsonSerializable(typeof(LedTestPatternBody))]

// Zones model - device structure, partition save bodies, device-scoped LED map.
[JsonSerializable(typeof(DeviceStructureResponse))]
[JsonSerializable(typeof(StructureSegmentDto))]
[JsonSerializable(typeof(List<StructureSegmentDto>))]
[JsonSerializable(typeof(StructureZoneDto))]
[JsonSerializable(typeof(List<StructureZoneDto>))]
[JsonSerializable(typeof(SaveZonePartitionBody))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ZoneDef))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.ZoneDef>))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ZoneSlice))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.ZoneSlice>))]
[JsonSerializable(typeof(DeviceMapResponse))]
[JsonSerializable(typeof(DeviceMapSegmentDto))]
[JsonSerializable(typeof(List<DeviceMapSegmentDto>))]
[JsonSerializable(typeof(DeviceMapLedDto))]
[JsonSerializable(typeof(List<DeviceMapLedDto>))]
[JsonSerializable(typeof(SaveDeviceMapBody))]
[JsonSerializable(typeof(Nexus.Service.Persistence.SegmentLedOverride))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.SegmentLedOverride>))]

// Community LED mappings - artifact (wire + .nexusmap), registry proxy
// DTOs, cloud signal bodies, and the auto-applied toast frame.
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingArtifact))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingDeviceInfo))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingDeviceMatch))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingZoneSignature))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingZoneSignature>))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingZone))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingZone>))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingLed))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingLed>))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingGroup))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingGroup>))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingLedRange))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingLedRange>))]
[JsonSerializable(typeof(CommunityMapping))]
[JsonSerializable(typeof(List<CommunityMapping>))]
[JsonSerializable(typeof(CommunityMappingList))]
[JsonSerializable(typeof(DeviceMappingsResponse))]
[JsonSerializable(typeof(AppliedMappingSummary))]
[JsonSerializable(typeof(ApplyMappingBody))]
[JsonSerializable(typeof(MappingsAvailableResponse))]
[JsonSerializable(typeof(PublishMappingResponse))]
[JsonSerializable(typeof(ExportMappingResponse))]
[JsonSerializable(typeof(PublishCloudBody))]
[JsonSerializable(typeof(AdoptCloudBody))]
[JsonSerializable(typeof(RevokeCloudBody))]
[JsonSerializable(typeof(DevicesSeenCloudBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.MappingAutoAppliedFrame))]

// Smart (network) lights
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.SmartLightDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.SmartLights.SmartLightDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.GetSmartLightsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.DiscoverSmartLightsBody))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.DiscoveredSmartLightDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.SmartLights.DiscoveredSmartLightDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.DiscoverSmartLightsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.PairSmartLightBody))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.PairSmartLightResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.EnableSmartLightBody))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.BrandEnableBody))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<string, bool>))]

// Keeb
[JsonSerializable(typeof(KeyboardState))]
[JsonSerializable(typeof(GetKeebSettingsResponse))]
[JsonSerializable(typeof(GetRotaryFunctionsResponse))]
[JsonSerializable(typeof(SetRotaryWheelsBody))]
[JsonSerializable(typeof(SetRotarySensitivityBody))]
[JsonSerializable(typeof(SetFirmwareLightingBody))]
[JsonSerializable(typeof(SetPassiveLightingBody))]
[JsonSerializable(typeof(SetGameModeBody))]
[JsonSerializable(typeof(GetMacroResponse))]
[JsonSerializable(typeof(SetMacroBody))]
[JsonSerializable(typeof(InputterBody))]

// Displays
[JsonSerializable(typeof(Y70RotationParams))]
[JsonSerializable(typeof(Y70BrightnessResponse))]
[JsonSerializable(typeof(Y70BrightnessParams))]
[JsonSerializable(typeof(Y70ToggleScreenResponse))]
[JsonSerializable(typeof(Y70ToggleScreenParams))]

// Activity
[JsonSerializable(typeof(FocusSession))]
[JsonSerializable(typeof(AppUsage))]
[JsonSerializable(typeof(List<AppUsage>))]
[JsonSerializable(typeof(IReadOnlyList<AppUsage>))]
[JsonSerializable(typeof(DayBreakdown))]
[JsonSerializable(typeof(DayTotal))]
[JsonSerializable(typeof(List<DayTotal>))]
[JsonSerializable(typeof(IReadOnlyList<DayTotal>))]
[JsonSerializable(typeof(AppHistory))]
[JsonSerializable(typeof(List<long>))]
[JsonSerializable(typeof(DeleteResponse))]
[JsonSerializable(typeof(TrackingStatus))]
[JsonSerializable(typeof(SetTrackingBody))]
[JsonSerializable(typeof(NetworkProcessInfo))]
[JsonSerializable(typeof(List<NetworkProcessInfo>))]
[JsonSerializable(typeof(IEnumerable<NetworkProcessInfo>))]
[JsonSerializable(typeof(List<Detected>))]
[JsonSerializable(typeof(KillAppResponse))]
[JsonSerializable(typeof(Dictionary<string, MediaSession>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, MediaSession>))]
[JsonSerializable(typeof(MediaControlBody))]
[JsonSerializable(typeof(VolumeState))]
[JsonSerializable(typeof(SetVolumeBody))]
[JsonSerializable(typeof(SetMutedBody))]
[JsonSerializable(typeof(SystemAccentResponse))]
[JsonSerializable(typeof(SendKeysBody))]
[JsonSerializable(typeof(SendTextBody))]
[JsonSerializable(typeof(OpenPathBody))]
[JsonSerializable(typeof(AudioDevice))]
[JsonSerializable(typeof(List<AudioDevice>))]
[JsonSerializable(typeof(AudioDeviceList))]
[JsonSerializable(typeof(SetAudioDefaultBody))]
[JsonSerializable(typeof(GetAllShortcutsResponse))]
[JsonSerializable(typeof(GetShortcutResponse))]
[JsonSerializable(typeof(MusicResult))]

// Lifecycle
[JsonSerializable(typeof(SetWillStartParams))]
[JsonSerializable(typeof(WillStartResponse))]
[JsonSerializable(typeof(PawnIoStatus))]

// Processes
[JsonSerializable(typeof(ProcessInfo))]
[JsonSerializable(typeof(List<ProcessInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ProcessInfo>))]
[JsonSerializable(typeof(IEnumerable<ProcessInfo>))]

// Activity broadcaster (WebSocket push frames)
[JsonSerializable(typeof(ProcessFrame))]
[JsonSerializable(typeof(Nexus.Service.Activity.GpuProcessFrame))]
[JsonSerializable(typeof(NetworkFrame))]
[JsonSerializable(typeof(ScreenTimeFrame))]

// Monitoring (multiplexed WebSocket composite frame)
[JsonSerializable(typeof(Nexus.Service.Models.Monitoring.MonitoringFrame))]

// Benchmarks
[JsonSerializable(typeof(BenchmarkSubScore))]
[JsonSerializable(typeof(List<BenchmarkSubScore>))]
[JsonSerializable(typeof(BenchmarkPhaseProgress))]
[JsonSerializable(typeof(BenchmarkProgressFrame))]
[JsonSerializable(typeof(BenchmarkResult))]
[JsonSerializable(typeof(HardwareIdentity))]
[JsonSerializable(typeof(StartBenchmarkResponse))]
[JsonSerializable(typeof(StartBenchmarkBody))]

[JsonSerializable(typeof(float[]))]
[JsonSerializable(typeof(List<string>))]

// Helper IPC transport + per-domain payloads. Grouped by domain for
// readability. Types themselves live under src/Helper/ and
// src/Helper/Domains/; this file is the single AOT JSON-registration
// surface (the JsonSourceGenerator does not deal well with partial
// declarations of JsonSerializerContext spread across many files).
[JsonSerializable(typeof(HelperEnvelope))]
[JsonSerializable(typeof(HelperResult))]
[JsonSerializable(typeof(HelperHello))]
#if WINDOWS
// Helper IPC payload types live under `#if WINDOWS` so they only register
// where the helper actually runs. Same gate as the per-domain files under
// src/Helper/Domains/; without this the non-Windows TFM does not compile
// because Nexus.Service.Helper.Domains is absent there.
// Lifecycle
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.HelperShutdownPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OverlayPrefsChangedPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ServiceRequestStopPayload))]
// Diagnostics
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenLogsPayload))]
// Tray
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TraySetVisiblePayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TrayPairNoticePayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TrayNoticePayload))]
// Clipboard
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ClipboardSetTextPayload))]
// Screen-time
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenTimeSessionPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenTimeFocusPayload))]
// Media
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.MediaSnapshotPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.MediaControlPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.AlbumArtRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.AlbumArtResult))]
// Brightness
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayBrightnessRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.StringResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.NullableIntResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayVcpResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.BoolResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayListResult))]
// Orientation
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayOrientationRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayOrientationResult))]
// Monitors
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.MonitorEnumerateRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.MonitorListResult))]
// Display topology
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayTopologyRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayTopologyResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplaysChangedPayload))]
// Screen mirror
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenMirrorStartPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenMirrorStopPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenMirrorFramePayload))]
// Shortcuts (Start-menu app enumeration runs in the user-session helper)
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutsRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutListResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutOneResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutIconResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutBoolResult))]
// Native file/folder picker (IFileOpenDialog runs in the user-session helper)
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.FileDialogRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.FileDialogResult))]
// System launch (open-settings, open-url, open-file — user-session helper handles foreground)
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenSettingsPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenUrlPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenFilePayload))]
#endif

// Apps - manifest + listings (nexus.app/1 schema, sandboxed widget.mjs runtime)
[JsonSerializable(typeof(AppManifest))]
[JsonSerializable(typeof(AppManifestAuthor))]
[JsonSerializable(typeof(AppManifestViewport))]
[JsonSerializable(typeof(AppManifestCapabilities))]
[JsonSerializable(typeof(AppManifestSettingEntry))]
[JsonSerializable(typeof(List<AppManifestSettingEntry>))]
[JsonSerializable(typeof(AppActionAckDto))]
[JsonSerializable(typeof(AppCoolingStateDto))]
[JsonSerializable(typeof(ScreentimeHistoryEntryDto))]
[JsonSerializable(typeof(ScreentimeFocusDto))]
[JsonSerializable(typeof(ScreentimeTodayDto))]
[JsonSerializable(typeof(List<ScreentimeHistoryEntryDto>))]
[JsonSerializable(typeof(AppInstalledListing))]
[JsonSerializable(typeof(AppInstalledListingResponse))]
[JsonSerializable(typeof(List<AppInstalledListing>))]
[JsonSerializable(typeof(AppCatalogEntry))]
[JsonSerializable(typeof(AppCatalogResponse))]
[JsonSerializable(typeof(List<AppCatalogEntry>))]
[JsonSerializable(typeof(AppInstallRequest))]
[JsonSerializable(typeof(AppInstallResponse))]
[JsonSerializable(typeof(AppCodeSessionResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.OpenUrlRequest))]
// Widgets - settings
[JsonSerializable(typeof(WidgetSettingsDocument))]
[JsonSerializable(typeof(WidgetSettingsPatch))]
[JsonSerializable(typeof(Dictionary<string, System.Text.Json.JsonElement>))]
// Widgets - proxy
[JsonSerializable(typeof(AppProxyRequest))]
[JsonSerializable(typeof(AppProxyResponse))]
[JsonSerializable(typeof(AppDispatchRequest))]
[JsonSerializable(typeof(AppDispatchResponse))]

// Conflict warning system - sidebar alarm for competing third-party apps.
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.DetectedConflict))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Conflicts.DetectedConflict>))]
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.GetConflictsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.KillConflictBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.KillConflictResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.ConflictsFrame))]

// Install-time defaults table - read once on startup from the embedded
// data/install-defaults.json resource. Nested POCOs are picked up
// transitively by the source generator.
[JsonSerializable(typeof(Nexus.Service.Defaults.InstallDefaultsDocument))]

// Fleet telemetry heartbeat payload (anonymous).
[JsonSerializable(typeof(Nexus.Service.Telemetry.HeartbeatPayload))]

// Phone-as-webcam control surface.
[JsonSerializable(typeof(Nexus.Service.Models.Webcam.WebcamStartRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Webcam.WebcamStatusResponse))]

// Store - cloud account link, library proxy, install pipeline.
[JsonSerializable(typeof(Nexus.Service.Store.CloudDeviceGrantStartResponse))]
[JsonSerializable(typeof(Nexus.Service.Store.CloudDeviceGrantPollRequest))]
[JsonSerializable(typeof(Nexus.Service.Store.CloudDeviceGrantPollResponse))]
[JsonSerializable(typeof(Nexus.Service.Store.CloudAccountInfo))]
[JsonSerializable(typeof(Nexus.Service.Store.CloudLibraryResponse))]
[JsonSerializable(typeof(Nexus.Service.Store.CloudEntitlement))]
[JsonSerializable(typeof(Nexus.Service.Store.CloudInstallRecord))]
[JsonSerializable(typeof(Nexus.Service.Store.CloudAppDownloadInfo))]
[JsonSerializable(typeof(Nexus.Service.Store.CloudInstallReport))]
[JsonSerializable(typeof(Nexus.Service.Store.StoreAccountLinkStartResponse))]
[JsonSerializable(typeof(Nexus.Service.Store.StoreAccountStatusResponse))]
[JsonSerializable(typeof(Nexus.Service.Store.StoreAccountInfo))]
[JsonSerializable(typeof(Nexus.Service.Store.StoreInstallResponse))]
[JsonSerializable(typeof(Nexus.Service.Store.StoreInstallRequest))]

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
public partial class AppJsonContext : JsonSerializerContext;
