using System.Collections.Generic;
using System.Text.Json.Serialization;
using Nexus.Service.Activity;
using Nexus.Service.Integrations.HomeAssistant;
using Nexus.Service.Helper;
using Nexus.Service.Models;
using Nexus.Service.Models.Activity;
using Nexus.Service.Models.Benchmarks;
using Nexus.Service.Models.Cooling;
using Nexus.Service.Models.Devices;
using Nexus.Service.Models.Discord;
using Nexus.Service.Models.Lifecycle;
using Nexus.Service.Models.Lighting;
using Nexus.Service.Models.Obs;
using Nexus.Service.Models.Peripherals;
using Nexus.Service.Models.Peripherals.Keeb;
using Nexus.Service.Models.Peripherals.QSeries;
using Nexus.Service.Models.Peripherals.Y70;
using Nexus.Service.Models.Sensors;
using Nexus.Service.Models.Steam;
using Nexus.Service.Models.Update;
using Nexus.Service.Models.Widgets;
using Nexus.Service.Platform;
using Nexus.Service.Routes;
using Nexus.Service.Update;

namespace Nexus.Service.Serialization;

// Ping + Auth
[JsonSerializable(typeof(ApiResponse))]
[JsonSerializable(typeof(PingResponse))]
[JsonSerializable(typeof(PairResponse))]

// System / sensors
[JsonSerializable(typeof(PerformanceSnapshot))]
[JsonSerializable(typeof(HardwareSensor))]
[JsonSerializable(typeof(List<HardwareSensor>))]
[JsonSerializable(typeof(IReadOnlyList<HardwareSensor>))]
[JsonSerializable(typeof(HardwareComponent))]
[JsonSerializable(typeof(List<HardwareComponent>))]
[JsonSerializable(typeof(StorageComponent))]
[JsonSerializable(typeof(Dictionary<string, StorageComponent>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, StorageComponent>))]
[JsonSerializable(typeof(StorageDriveInfo))]
[JsonSerializable(typeof(SensorExtras))]
[JsonSerializable(typeof(GetModelResponse))]
[JsonSerializable(typeof(GetGpuModelsResponse))]
[JsonSerializable(typeof(CpuHealthResponse))]
[JsonSerializable(typeof(GetStoragePartitionsResponse))]
[JsonSerializable(typeof(GetDriveStorageResponse))]
[JsonSerializable(typeof(SystemSpecsResponse))]
[JsonSerializable(typeof(GetPollingRateResponse))]

// Cooling
[JsonSerializable(typeof(CoolingComponent))]
[JsonSerializable(typeof(GetAllCoolingResponse))]
[JsonSerializable(typeof(SetCurvesBody))]
[JsonSerializable(typeof(GetCurvesResponse))]
[JsonSerializable(typeof(CoolingWarning))]
[JsonSerializable(typeof(List<CoolingWarning>))]
[JsonSerializable(typeof(GetCoolingWarningsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cooling.GraphPoint), TypeInfoPropertyName = "CoolingGraphPoint")]
[JsonSerializable(typeof(List<Nexus.Service.Models.Cooling.GraphPoint>), TypeInfoPropertyName = "CoolingListGraphPoint")]

// NP50 device state surface
[JsonSerializable(typeof(Nexus.Service.Routes.Np50StateResponse))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50State))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50HubInfo))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50Port))]
[JsonSerializable(typeof(List<Nexus.Service.Peripherals.Hyte.Np50.Np50Port>))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50FanDevice))]
[JsonSerializable(typeof(List<Nexus.Service.Peripherals.Hyte.Np50.Np50FanDevice>))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50WarningDetail))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Hyte.Np50.Np50PortWarning))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50LightingRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50LedColor))]
[JsonSerializable(typeof(List<Nexus.Service.Routes.Np50LedColor>))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareDefaultsResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareDefaultsRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareAnimationResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50FirmwareAnimationRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.Np50CoolingModeRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.MiniHubCoolingModeRequest))]

// SmartHub device state surface
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubFanResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubFanResponse[]))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubFwSettingResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubFwSettingRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubFirmwareControlRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubCompositionResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.SmartHubCompositionRequest))]

// Q-series cooler device surface
[JsonSerializable(typeof(Nexus.Service.Routes.QSeriesCoolerStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.QSeriesControlModeRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.QSeriesTurboRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.QSeriesFirmwareCurveResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.QSeriesFirmwareCurveRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.QSeriesCurvePointDto))]

// Tryx Panorama device surface
[JsonSerializable(typeof(Nexus.Service.Peripherals.Tryx.Panorama.TryxPanoramaState))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxStatusResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxOverlaySnapshot))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxMediaImportResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxPresetListResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxMediaListResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxPresetItem))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxMediaItem))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxAckResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxCloudCatalogResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxCloudMaterialDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxCloudInstallRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxEnableRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxBrightnessRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxPresetRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxMediaSelectRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxMediaDeleteRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxOverlayRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxOverlayItem))]
[JsonSerializable(typeof(Nexus.Service.Routes.TryxOverlayItem[]))]

// Fan control
[JsonSerializable(typeof(FanChannel))]
[JsonSerializable(typeof(List<FanChannel>))]
[JsonSerializable(typeof(TemperatureSource))]
[JsonSerializable(typeof(List<TemperatureSource>))]
[JsonSerializable(typeof(GetFanChannelsResponse))]
[JsonSerializable(typeof(GetTemperatureSourcesResponse))]
[JsonSerializable(typeof(SetFanSpeedBody))]
[JsonSerializable(typeof(SetFanNameBody))]
[JsonSerializable(typeof(SetFanLockBody))]
[JsonSerializable(typeof(SetFanSpeedResponse))]
[JsonSerializable(typeof(CurveOutputState))]
[JsonSerializable(typeof(CurveCalculation))]
[JsonSerializable(typeof(CurveCalculationsFrame))]
[JsonSerializable(typeof(FanProfile))]
[JsonSerializable(typeof(List<FanProfile>))]
[JsonSerializable(typeof(GetProfilesResponse))]
[JsonSerializable(typeof(ApplyProfileResponse))]
[JsonSerializable(typeof(StartupModeBody))]
[JsonSerializable(typeof(StartupModeDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.TelemetryConsentBody))]
[JsonSerializable(typeof(Nexus.Service.Routes.TelemetryConsentDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.OnboardingStatusDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.ClientMemBody))]
[JsonSerializable(typeof(FanCalibration))]
[JsonSerializable(typeof(List<FanCalibration>))]
[JsonSerializable(typeof(FanCalibrationPoint))]
[JsonSerializable(typeof(List<FanCalibrationPoint>))]
[JsonSerializable(typeof(FanCalibrationProgress))]
[JsonSerializable(typeof(StartCalibrationBody))]
[JsonSerializable(typeof(CoolingStatusResponse))]
[JsonSerializable(typeof(LightingStatusResponse))]
[JsonSerializable(typeof(List<float>))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.MusicReactiveBody))]
[JsonSerializable(typeof(CalibrationStartResponse))]
[JsonSerializable(typeof(GetCalibrationsResponse))]

// Profiles
[JsonSerializable(typeof(Nexus.Service.Persistence.ProfileManifest))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ProfileEntry))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.ProfileEntry>))]
[JsonSerializable(typeof(Nexus.Service.Persistence.GraphPoint), TypeInfoPropertyName = "PersistenceGraphPoint")]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.GraphPoint>), TypeInfoPropertyName = "PersistenceListGraphPoint")]
[JsonSerializable(typeof(Nexus.Service.Persistence.UiSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.UiSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.UnitsSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.UnitsSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ThemeSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.MonitoringSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.OverlaySettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelLayoutsDefaults))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelLayoutDefault))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelLayoutWidget))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.PanelLayoutWidget>))]
[JsonSerializable(typeof(Nexus.Service.Persistence.Preferences))]
[JsonSerializable(typeof(Nexus.Service.Persistence.CoolingPrefs))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PreferencesPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ThemeSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PanelSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.OverlaySettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.MonitoringSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.CoolingPrefsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.DiagnosticsSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.DiagnosticsThresholds))]
[JsonSerializable(typeof(Nexus.Service.Persistence.DiagnosticsNotifications))]
[JsonSerializable(typeof(Nexus.Service.Persistence.DiagnosticsComponents))]
[JsonSerializable(typeof(Nexus.Service.Persistence.DiagnosticsSettingsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.DiagnosticsThresholdsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.DiagnosticsNotificationsPatch))]
[JsonSerializable(typeof(Nexus.Service.Persistence.DiagnosticsComponentsPatch))]

// Panel widget engine - per-device records, layouts, control-state push frames.
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelLayoutDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPageDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelWidgetDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.PanelPageDto>))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.PanelWidgetDto>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, System.Text.Json.JsonElement>>))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceRecord))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceCapabilities))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.XeneonEdgeSettingsDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDevicePatch))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceCreateBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceListResponse))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.PanelDeviceRecord>))]
[JsonSerializable(typeof(Dictionary<string, Nexus.Service.Models.Panel.PanelDeviceRecord>))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PrefsChangedFrame))]

// Desktop widgets - floating panel widgets on the Windows desktop.
[JsonSerializable(typeof(Nexus.Service.Models.Panel.OverlayWidgetDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.OverlayWidgetCreateBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.OverlayWidgetPatch))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.OverlayLockAllBody))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.OverlayWidgetDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.LightingChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.CoolingChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.VolumeChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PairQrRefreshFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.SystemAccentFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.CoolingWarningsChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.DevicesChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelDeviceChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairQrResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneClaimBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneClaimResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneServiceInfoResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneSessionNameBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelHostNameBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelHostNameResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneSessionsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhoneSessionDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.PanelPhoneSessionDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelStatusResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RemoteControlStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RemoteControlToggleRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayToggleRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayHostHello))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayClaimRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayClaimResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayHttpRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.RelayHttpResponse))]
[JsonSerializable(typeof(Nexus.Service.Relay.RelayDirectoryResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PairBroadcastStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PairBroadcastSetRequest))]

// WebRTC DataChannel direct P2P transport
[JsonSerializable(typeof(Nexus.Service.Rtc.RtcOfferRequest))]
[JsonSerializable(typeof(Nexus.Service.Rtc.RtcAnswerResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PairWifiInitiateRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeStartResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeSubmitBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeSubmitResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeConfirmBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeConfirmResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeHostDecisionBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeHostDecisionResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelPhonePairCodeRequestFrame))]

// Displays (system monitors: brightness + DDC/CI VCP)
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Displays.DisplayDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayCapabilitiesDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBrightnessControlDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBrightnessWritePolicy))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBrightnessDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBrightnessParams))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayVcpDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayVcpParams))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayListResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.RawDisplayInfo))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Displays.RawDisplayInfo>))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayBoundsDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplaySizeDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayTopologyEntryDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayTopologyResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplaysChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.PanelPromoteBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayAssignmentDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayAssignmentsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.DisplayRotationBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.TouchMapDigitizerInfo))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Displays.TouchMapDigitizerInfo>))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.TouchMapDisplayInfo))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Displays.TouchMapDisplayInfo>))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.TouchMapSnapshot))]
[JsonSerializable(typeof(Nexus.Service.Models.Displays.TouchMappingRepairResponse))]

// Streamed panels (off-screen render in the overlay, H.264 to a USB device).
[JsonSerializable(typeof(Nexus.Service.Models.Panel.StreamAssignmentDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.StreamAssignmentsResponse))]

// Weather
[JsonSerializable(typeof(Nexus.Service.Models.Weather.WeatherSnapshot))]
[JsonSerializable(typeof(Nexus.Service.Models.Weather.WeatherHourlyForecast))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Weather.WeatherHourlyForecast>))]
[JsonSerializable(typeof(Nexus.Service.Models.Weather.WeatherDailyForecast))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Weather.WeatherDailyForecast>))]
[JsonSerializable(typeof(Nexus.Service.Platform.Weather.IpLocation))]
[JsonSerializable(typeof(Nexus.Service.Platform.Weather.OpenMeteoResponse))]
[JsonSerializable(typeof(Nexus.Service.Platform.Weather.OpenMeteoCurrent))]
[JsonSerializable(typeof(Nexus.Service.Platform.Weather.OpenMeteoHourly))]
[JsonSerializable(typeof(Nexus.Service.Platform.Weather.OpenMeteoDaily))]
[JsonSerializable(typeof(Nexus.Service.Models.Weather.WeatherGeocodeResult))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Weather.WeatherGeocodeResult>))]
[JsonSerializable(typeof(Nexus.Service.Models.Weather.WeatherGeocodeResponse))]
[JsonSerializable(typeof(Nexus.Service.Platform.Weather.OpenMeteoGeocodeResponse))]
[JsonSerializable(typeof(Nexus.Service.Platform.Weather.OpenMeteoGeocodeResult))]
[JsonSerializable(typeof(Nexus.Service.Platform.Weather.OpenMeteoGeocodeResult[]))]

// Stocks
[JsonSerializable(typeof(Nexus.Service.Models.Stocks.StockQuote))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Stocks.StockQuote>))]
[JsonSerializable(typeof(List<double>))]
[JsonSerializable(typeof(Nexus.Service.Models.Stocks.StockQuotesResponse))]
[JsonSerializable(typeof(Nexus.Service.Platform.Stocks.YahooChartResponse))]
[JsonSerializable(typeof(Nexus.Service.Platform.Stocks.YahooChart))]
[JsonSerializable(typeof(Nexus.Service.Platform.Stocks.YahooChartError))]
[JsonSerializable(typeof(Nexus.Service.Platform.Stocks.YahooChartResult))]
[JsonSerializable(typeof(Nexus.Service.Platform.Stocks.YahooChartResult[]))]
[JsonSerializable(typeof(Nexus.Service.Platform.Stocks.YahooChartMeta))]
[JsonSerializable(typeof(Nexus.Service.Platform.Stocks.YahooChartIndicators))]
[JsonSerializable(typeof(Nexus.Service.Platform.Stocks.YahooChartQuote))]
[JsonSerializable(typeof(Nexus.Service.Platform.Stocks.YahooChartQuote[]))]
[JsonSerializable(typeof(double?[]))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.ListProfilesResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.ProfileResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.SwitchProfileResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.CreateProfileBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.RenameProfileBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.ProfileExport))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.SharingResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.SetPrimaryBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Profiles.SetCategorySharedBody))]

// Cloud accounts (api.hellonexus.com client) + local /cloud/... routes.
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudAvatarDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudAccountDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudAuthSession))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudRegisterRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudLoginRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudRefreshRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudLogoutRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudRecoveryStartRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudRecoveryPollRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudRecoveryPollResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudChangePasswordRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudChangeUsernameRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudSetPrivateRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudDeleteAccountRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudDevicePutRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudProfileSummaryDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Cloud.CloudProfileSummaryDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudProfileDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudPutProfileRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudPutProfileResult))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudAvatarUploadResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudErrorBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudAccountSummaryDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Cloud.CloudAccountSummaryDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudAccountsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudFailureResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudRegisterBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudLoginBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudLoginResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudLogoutBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudRecoveryStartBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudRecoveryStatusResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudPasswordBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudUsernameBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudSetPrivateBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudDeleteAccountBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudAvatarResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudSyncConflictDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Cloud.CloudSyncConflictDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudSyncProfileDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Cloud.CloudSyncProfileDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudSyncStatusResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Cloud.CloudSyncResolveBody))]

// Media library
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaItem))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Media.MediaItem>))]
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaLibraryResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaImportResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Transfer.TransferItemsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Transfer.TransferClipboardBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Transfer.TransferReceivedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaPlayResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaCurrentResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Media.MediaStageResponse))]
// Panel background media
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelBgItem))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Panel.PanelBgItem>))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelBgListResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelBgImportResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelBgResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.PanelBgStageResponse))]

// Gallery
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GallerySource))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Gallery.GallerySource>))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GallerySourcesFile))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GallerySourcesResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.AddGallerySourceBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GallerySourceMutationResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryItem))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Gallery.GalleryItem>))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryItemsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryPickBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryPickResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Gallery.GalleryExcludeBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.GalleryChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.MediaLibraryChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.DesktopWallpaperChangedFrame))]

// Lighting
[JsonSerializable(typeof(AudioStateSnapshot))]
[JsonSerializable(typeof(ShaderSourceResponse))]
[JsonSerializable(typeof(CurrentSyncResponse))]
[JsonSerializable(typeof(BrightnessScale))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.GlobalBrightnessBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.RenderGpuBody))]
[JsonSerializable(typeof(SpeedScale))]
[JsonSerializable(typeof(AnimateHeadlessStart))]
[JsonSerializable(typeof(SetAnimateTemplatesBody))]
[JsonSerializable(typeof(ShaderParam))]
[JsonSerializable(typeof(List<ShaderParam>))]
[JsonSerializable(typeof(Nexus.Service.Persistence.AnimateSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.AnimateEffectState))]
[JsonSerializable(typeof(Nexus.Service.Persistence.AnimateEffectTemplates))]
[JsonSerializable(typeof(Nexus.Service.Persistence.StaticColorSettings))]
[JsonSerializable(typeof(Dictionary<string, Nexus.Service.Persistence.AnimateEffectState>))]
[JsonSerializable(typeof(Dictionary<string, Nexus.Service.Persistence.AnimateEffectTemplates>))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.AnimateEffectState>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, float>>))]
[JsonSerializable(typeof(MusicHeadlessStart))]
[JsonSerializable(typeof(ScreenHeadlessStart))]
[JsonSerializable(typeof(ScreenSyncOptions))]
[JsonSerializable(typeof(ScreenSyncMonitor))]
[JsonSerializable(typeof(List<ScreenSyncMonitor>))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.GameSyncFrameBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.GameSyncDeviceInfo))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.GameSyncStateResponse))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Lighting.GameSyncDeviceInfo>))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.DetectedGame))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Lighting.DetectedGame>))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.GameSyncGamesResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiPayload))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiProvider))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiPlayer))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiPlayerState))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiRound))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiBomb))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiMap))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiTeamScore))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiPhaseCountdowns))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.Cs2GsiAuth))]
[JsonSerializable(typeof(Nexus.Service.Models.Lighting.PostProcessBody))]
[JsonSerializable(typeof(Nexus.Service.Persistence.PostProcessSettings))]

// OBS
[JsonSerializable(typeof(ObsConfigResponse))]
[JsonSerializable(typeof(ObsConfigBody))]
[JsonSerializable(typeof(ObsStatusResponse))]
[JsonSerializable(typeof(ObsScene))]
[JsonSerializable(typeof(List<ObsScene>))]
[JsonSerializable(typeof(ObsSetSceneBody))]

// Steam
[JsonSerializable(typeof(SteamConfigResponse))]
[JsonSerializable(typeof(SteamConfigBody))]
[JsonSerializable(typeof(SteamStatusResponse))]
[JsonSerializable(typeof(SteamProfileResponse))]
[JsonSerializable(typeof(SteamPlayerSummary))]
[JsonSerializable(typeof(SteamRecentGame))]
[JsonSerializable(typeof(List<SteamRecentGame>))]
[JsonSerializable(typeof(SteamOwnedGame))]
[JsonSerializable(typeof(List<SteamOwnedGame>))]
[JsonSerializable(typeof(SteamFriendSummary))]
[JsonSerializable(typeof(List<SteamFriendSummary>))]
[JsonSerializable(typeof(SteamAchievement))]
[JsonSerializable(typeof(List<SteamAchievement>))]
[JsonSerializable(typeof(SteamCurrentPlayers))]
[JsonSerializable(typeof(SteamNewsItem))]
[JsonSerializable(typeof(List<SteamNewsItem>))]
[JsonSerializable(typeof(SteamGlobalAchievement))]
[JsonSerializable(typeof(List<SteamGlobalAchievement>))]
[JsonSerializable(typeof(SteamUserStat))]
[JsonSerializable(typeof(List<SteamUserStat>))]
[JsonSerializable(typeof(SteamAppDetails))]

// Discord
[JsonSerializable(typeof(DiscordConfigResponse))]
[JsonSerializable(typeof(DiscordConfigBody))]
[JsonSerializable(typeof(DiscordStatusResponse))]
[JsonSerializable(typeof(DiscordUser))]
[JsonSerializable(typeof(DiscordGuild))]
[JsonSerializable(typeof(List<DiscordGuild>))]
[JsonSerializable(typeof(DiscordVoiceState))]
[JsonSerializable(typeof(DiscordVoiceParticipant))]
[JsonSerializable(typeof(List<DiscordVoiceParticipant>))]
[JsonSerializable(typeof(DiscordNotification))]
[JsonSerializable(typeof(List<DiscordNotification>))]
[JsonSerializable(typeof(DiscordOpenBody))]
[JsonSerializable(typeof(DiscordVoiceToggleBody))]

// Devices
[JsonSerializable(typeof(Nexus.Service.Persistence.DeviceLayout))]
[JsonSerializable(typeof(Dictionary<string, Nexus.Service.Persistence.DeviceLayout>))]
[JsonSerializable(typeof(SaveDeviceLayoutBody))]
[JsonSerializable(typeof(LayoutPresetDto))]
[JsonSerializable(typeof(List<LayoutPresetDto>))]
[JsonSerializable(typeof(LayoutPresetsResponse))]
[JsonSerializable(typeof(CreateLayoutPresetBody))]
[JsonSerializable(typeof(CreateLayoutPresetResponse))]
[JsonSerializable(typeof(UpdateLayoutPresetBody))]
[JsonSerializable(typeof(SetActivePresetBody))]
[JsonSerializable(typeof(DeletePresetResponse))]
[JsonSerializable(typeof(BatchApplyLayoutsBody))]
[JsonSerializable(typeof(DeviceListItem))]
[JsonSerializable(typeof(List<DeviceListItem>))]
[JsonSerializable(typeof(DeviceControlRequest))]
[JsonSerializable(typeof(UsbDeviceDetail))]
[JsonSerializable(typeof(List<UsbDeviceDetail>))]
[JsonSerializable(typeof(FirmwareStatusItem))]
[JsonSerializable(typeof(List<FirmwareStatusItem>))]
[JsonSerializable(typeof(FlashableImage))]
[JsonSerializable(typeof(List<FlashableImage>))]
[JsonSerializable(typeof(FlashRequest))]
[JsonSerializable(typeof(FlashStatusDto))]
[JsonSerializable(typeof(FlashStartResponse))]

// Peripherals (third-party mice/keyboards/headsets with protocol support)
[JsonSerializable(typeof(PeripheralDto))]
[JsonSerializable(typeof(List<PeripheralDto>))]
[JsonSerializable(typeof(GetPeripheralsResponse))]
[JsonSerializable(typeof(SupportedDeviceDto))]
[JsonSerializable(typeof(List<SupportedDeviceDto>))]
[JsonSerializable(typeof(GetSupportedDevicesResponse))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.OpenRgbSupportedDevicesFile))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.OpenRgbSupportedDeviceEntry))]
[JsonSerializable(typeof(List<Nexus.Service.Peripherals.OpenRgbSupportedDeviceEntry>))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Protocols.Razer.RazerMouseSpec))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.Protocols.Razer.RazerMouseSpecEntry))]
[JsonSerializable(typeof(List<Nexus.Service.Peripherals.Protocols.Razer.RazerMouseSpecEntry>))]
[JsonSerializable(typeof(DpiState))]
[JsonSerializable(typeof(PollingState))]
[JsonSerializable(typeof(BatteryState))]
[JsonSerializable(typeof(SleepState))]
[JsonSerializable(typeof(ToggleState))]
[JsonSerializable(typeof(SetDpiBody))]
[JsonSerializable(typeof(SetPollingBody))]
[JsonSerializable(typeof(SetSleepBody))]
[JsonSerializable(typeof(SetToggleBody))]
[JsonSerializable(typeof(IsDeviceConnectedResponse))]
[JsonSerializable(typeof(FirmwareVersionResponse))]
[JsonSerializable(typeof(GetCnvsSettingsResponse))]
[JsonSerializable(typeof(SetCnvsSettingsBody))]
[JsonSerializable(typeof(UpdateBody))]
[JsonSerializable(typeof(CheckForUpdateResponse))]
[JsonSerializable(typeof(UpdateResponse))]
[JsonSerializable(typeof(GetMotherboardLEDsResponse))]
[JsonSerializable(typeof(SetMotherboardLEDsBody))]
[JsonSerializable(typeof(CheckFirmwareFunctionBody))]
[JsonSerializable(typeof(CheckFirmwareFunctionResponse))]
[JsonSerializable(typeof(GetLightingDevicesResponse))]
[JsonSerializable(typeof(SetDisabledLedsBody))]
[JsonSerializable(typeof(SetLightingDevicePowerBody))]
[JsonSerializable(typeof(SetLightingDeviceControlledBody))]
[JsonSerializable(typeof(SetLightingDeviceBrightness))]
[JsonSerializable(typeof(SetLightingDeviceHue))]
[JsonSerializable(typeof(SetLightingDeviceSaturation))]
[JsonSerializable(typeof(SetLightingDeviceColor))]
[JsonSerializable(typeof(SetZoneLedCountBody))]
[JsonSerializable(typeof(IdentifyLightingDeviceBody))]
[JsonSerializable(typeof(LedMapResponse))]
[JsonSerializable(typeof(LedMapEntry))]
[JsonSerializable(typeof(List<LedMapEntry>))]
[JsonSerializable(typeof(SaveLedMapBody))]
[JsonSerializable(typeof(Nexus.Service.Persistence.LedPositionOverride))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.LedPositionOverride>))]
[JsonSerializable(typeof(LedHighlightBody))]
[JsonSerializable(typeof(LedTestPatternBody))]
[JsonSerializable(typeof(LedPreviewLayoutBody))]
[JsonSerializable(typeof(LedPreviewPosition))]
[JsonSerializable(typeof(List<LedPreviewPosition>))]

// Zones model - device structure, partition save bodies, device-scoped LED map.
[JsonSerializable(typeof(DeviceStructureResponse))]
[JsonSerializable(typeof(StructureSegmentDto))]
[JsonSerializable(typeof(List<StructureSegmentDto>))]
[JsonSerializable(typeof(StructureZoneDto))]
[JsonSerializable(typeof(List<StructureZoneDto>))]
[JsonSerializable(typeof(SaveZonePartitionBody))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ZoneDef))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.ZoneDef>))]
[JsonSerializable(typeof(Nexus.Service.Persistence.ZoneSlice))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.ZoneSlice>))]
[JsonSerializable(typeof(DeviceMapResponse))]
[JsonSerializable(typeof(DeviceMapSegmentDto))]
[JsonSerializable(typeof(List<DeviceMapSegmentDto>))]
[JsonSerializable(typeof(DeviceMapLedDto))]
[JsonSerializable(typeof(List<DeviceMapLedDto>))]
[JsonSerializable(typeof(SaveDeviceMapBody))]
[JsonSerializable(typeof(Nexus.Service.Persistence.SegmentLedOverride))]
[JsonSerializable(typeof(List<Nexus.Service.Persistence.SegmentLedOverride>))]

// Community LED mappings - artifact (wire + .nexusmap), registry proxy
// DTOs, cloud signal bodies, and the auto-applied toast frame.
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingArtifact))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingDeviceInfo))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingDeviceMatch))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingZoneSignature))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingZoneSignature>))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingZone))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingZone>))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingLed))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingLed>))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingGroup))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingGroup>))]
[JsonSerializable(typeof(Nexus.Service.Lighting.Mappings.MappingLedRange))]
[JsonSerializable(typeof(List<Nexus.Service.Lighting.Mappings.MappingLedRange>))]
[JsonSerializable(typeof(CommunityMapping))]
[JsonSerializable(typeof(List<CommunityMapping>))]
[JsonSerializable(typeof(CommunityMappingList))]
[JsonSerializable(typeof(DeviceMappingsResponse))]
[JsonSerializable(typeof(AppliedMappingSummary))]
[JsonSerializable(typeof(ApplyMappingBody))]
[JsonSerializable(typeof(MappingsAvailableResponse))]
[JsonSerializable(typeof(PublishMappingResponse))]
[JsonSerializable(typeof(ExportMappingResponse))]
[JsonSerializable(typeof(PublishCloudBody))]
[JsonSerializable(typeof(AdoptCloudBody))]
[JsonSerializable(typeof(RevokeCloudBody))]
[JsonSerializable(typeof(DevicesSeenCloudBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.MappingAutoAppliedFrame))]

// Smart (network) lights
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.SmartLightDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.SmartLights.SmartLightDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.GetSmartLightsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.DiscoverSmartLightsBody))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.DiscoveredSmartLightDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.SmartLights.DiscoveredSmartLightDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.DiscoverSmartLightsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.PairSmartLightBody))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.PairSmartLightResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.EnableSmartLightBody))]
[JsonSerializable(typeof(Nexus.Service.Models.SmartLights.BrandEnableBody))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<string, bool>))]

// Keeb
[JsonSerializable(typeof(KeyboardState))]
[JsonSerializable(typeof(GetKeebSettingsResponse))]
[JsonSerializable(typeof(GetRotaryFunctionsResponse))]
[JsonSerializable(typeof(SetRotaryWheelsBody))]
[JsonSerializable(typeof(SetFirmwareLightingBody))]
[JsonSerializable(typeof(SetPassiveLightingBody))]
[JsonSerializable(typeof(SetGameModeBody))]
[JsonSerializable(typeof(GetMacroResponse))]
[JsonSerializable(typeof(SetMacroBody))]
[JsonSerializable(typeof(SetMacroResponse))]
[JsonSerializable(typeof(SetLayerKeyBody))]
[JsonSerializable(typeof(SetLayerKeyResponse))]
[JsonSerializable(typeof(InputterBody))]

// Displays
[JsonSerializable(typeof(Y70RotationParams))]
[JsonSerializable(typeof(Y70BrightnessResponse))]
[JsonSerializable(typeof(Y70BrightnessParams))]
[JsonSerializable(typeof(Y70ToggleScreenResponse))]
[JsonSerializable(typeof(Y70ToggleScreenParams))]
[JsonSerializable(typeof(QSeriesRotationParams))]
[JsonSerializable(typeof(QSeriesDisplayParams))]

// Activity
[JsonSerializable(typeof(FocusSession))]
[JsonSerializable(typeof(AppUsage))]
[JsonSerializable(typeof(List<AppUsage>))]
[JsonSerializable(typeof(IReadOnlyList<AppUsage>))]
[JsonSerializable(typeof(DayBreakdown))]
[JsonSerializable(typeof(DayTotal))]
[JsonSerializable(typeof(List<DayTotal>))]
[JsonSerializable(typeof(IReadOnlyList<DayTotal>))]
[JsonSerializable(typeof(AppHistory))]
[JsonSerializable(typeof(List<long>))]
[JsonSerializable(typeof(DeleteResponse))]
[JsonSerializable(typeof(TrackingStatus))]
[JsonSerializable(typeof(SetTrackingBody))]
[JsonSerializable(typeof(NetworkProcessInfo))]
[JsonSerializable(typeof(List<NetworkProcessInfo>))]
[JsonSerializable(typeof(IEnumerable<NetworkProcessInfo>))]
[JsonSerializable(typeof(List<Detected>))]
[JsonSerializable(typeof(KillAppResponse))]
[JsonSerializable(typeof(Dictionary<string, MediaSession>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, MediaSession>))]
[JsonSerializable(typeof(MediaControlBody))]
[JsonSerializable(typeof(VolumeState))]
[JsonSerializable(typeof(SetVolumeBody))]
[JsonSerializable(typeof(SetMutedBody))]
[JsonSerializable(typeof(SystemAccentResponse))]
[JsonSerializable(typeof(SystemBootResponse))]
[JsonSerializable(typeof(SendKeysBody))]
[JsonSerializable(typeof(SendTextBody))]
[JsonSerializable(typeof(OpenPathBody))]
[JsonSerializable(typeof(PickPathBody))]
[JsonSerializable(typeof(PickPathResponse))]
[JsonSerializable(typeof(AudioDevice))]
[JsonSerializable(typeof(List<AudioDevice>))]
[JsonSerializable(typeof(AudioDeviceList))]
[JsonSerializable(typeof(SetAudioDefaultBody))]
[JsonSerializable(typeof(PlayAudioBody))]
[JsonSerializable(typeof(GetAllShortcutsResponse))]
[JsonSerializable(typeof(GetShortcutResponse))]
[JsonSerializable(typeof(Nexus.Service.Activity.IconCacheMeta))]

// Lifecycle
[JsonSerializable(typeof(SetWillStartParams))]
[JsonSerializable(typeof(WillStartResponse))]
[JsonSerializable(typeof(PawnIoStatus))]
[JsonSerializable(typeof(Nexus.Service.Lifecycle.PawnIoUpgradeMarker))]

// Processes
[JsonSerializable(typeof(ProcessInfo))]
[JsonSerializable(typeof(List<ProcessInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ProcessInfo>))]
[JsonSerializable(typeof(IEnumerable<ProcessInfo>))]

// Activity broadcaster (WebSocket push frames)
[JsonSerializable(typeof(ProcessFrame))]
[JsonSerializable(typeof(Nexus.Service.Activity.GpuProcessFrame))]
[JsonSerializable(typeof(NetworkFrame))]
[JsonSerializable(typeof(ScreenTimeFrame))]

// Monitoring (multiplexed WebSocket composite frame)
[JsonSerializable(typeof(Nexus.Service.Models.Monitoring.MonitoringFrame))]

// Benchmarks
[JsonSerializable(typeof(BenchmarkSubScore))]
[JsonSerializable(typeof(List<BenchmarkSubScore>))]
[JsonSerializable(typeof(BenchmarkPhaseProgress))]
[JsonSerializable(typeof(BenchmarkProgressFrame))]
[JsonSerializable(typeof(BenchmarkResult))]
[JsonSerializable(typeof(HardwareIdentity))]
[JsonSerializable(typeof(StartBenchmarkResponse))]
[JsonSerializable(typeof(StartBenchmarkBody))]
[JsonSerializable(typeof(BenchmarkBaselines))]
[JsonSerializable(typeof(ClpeakResult))]
[JsonSerializable(typeof(ClpeakEntry))]
[JsonSerializable(typeof(ClpeakEntry[]))]
[JsonSerializable(typeof(Dictionary<string, string>))]

[JsonSerializable(typeof(float[]))]
[JsonSerializable(typeof(List<string>))]

// Helper IPC transport + per-domain payloads. Grouped by domain for
// readability. Types themselves live under src/Helper/ and
// src/Helper/Domains/; this file is the single AOT JSON-registration
// surface (the JsonSourceGenerator does not deal well with partial
// declarations of JsonSerializerContext spread across many files).
[JsonSerializable(typeof(HelperEnvelope))]
[JsonSerializable(typeof(HelperResult))]
[JsonSerializable(typeof(HelperHello))]
#if WINDOWS
// Helper IPC payload types live under `#if WINDOWS` so they only register
// where the helper actually runs. Same gate as the per-domain files under
// src/Helper/Domains/; without this the non-Windows TFM does not compile
// because Nexus.Service.Helper.Domains is absent there.
// Lifecycle
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.HelperShutdownPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OverlayPrefsChangedPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ServiceRequestStopPayload))]
// Diagnostics
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenLogsPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenEventViewerPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenDeviceManagerPayload))]
// Tray
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TraySetVisiblePayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TrayPairNoticePayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TrayNoticePayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TrayUpdateReadyPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TrayOpenDashboardPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TrayShowUpdaterWindowPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TrayCloseUpdaterWindowPayload))]
// Clipboard
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ClipboardSetTextPayload))]
// Screen-time
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenTimeSessionPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenTimeFocusPayload))]
// Media
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.MediaSnapshotPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.MediaControlPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.AlbumArtRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.AlbumArtResult))]
// Brightness
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayBrightnessRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.StringResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.NullableIntResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayVcpResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.BoolResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayListResult))]
// Orientation
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayOrientationRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayOrientationResult))]
// Monitors
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.MonitorEnumerateRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.MonitorListResult))]
// Display topology
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayTopologyRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplayTopologyResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.DisplaysChangedPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.TouchMapRequest))]
// Screen mirror
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenMirrorStartPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenMirrorStopPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ScreenMirrorFramePayload))]
// Shortcuts (Start-menu app enumeration runs in the user-session helper)
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutsRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutListResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutOneResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutIconResult))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ShortcutBoolResult))]
// Native file/folder picker (IFileOpenDialog runs in the user-session helper)
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.FileDialogRequest))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.FileDialogResult))]
// System launch (open-settings, open-url, open-file - user-session helper handles foreground)
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenSettingsPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenUrlPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.OpenFilePayload))]
// Profiles pipe push/switch
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ProfileListPayload))]
[JsonSerializable(typeof(Nexus.Service.Helper.Domains.ProfileSwitchPayload))]
#endif

// Apps - manifest + listings (nexus.app/1 schema, sandboxed widget.mjs runtime)
[JsonSerializable(typeof(AppManifest))]
[JsonSerializable(typeof(AppManifestAuthor))]
[JsonSerializable(typeof(AppManifestViewport))]
[JsonSerializable(typeof(AppManifestCapabilities))]
[JsonSerializable(typeof(AppManifestSettingEntry))]
[JsonSerializable(typeof(List<AppManifestSettingEntry>))]
[JsonSerializable(typeof(AppActionAckDto))]
[JsonSerializable(typeof(AppCoolingStateDto))]
[JsonSerializable(typeof(ScreentimeHistoryEntryDto))]
[JsonSerializable(typeof(ScreentimeFocusDto))]
[JsonSerializable(typeof(ScreentimeTodayDto))]
[JsonSerializable(typeof(List<ScreentimeHistoryEntryDto>))]
[JsonSerializable(typeof(SystemInfoResponse))]
[JsonSerializable(typeof(AppInstalledListing))]
[JsonSerializable(typeof(AppInstalledListingResponse))]
[JsonSerializable(typeof(List<AppInstalledListing>))]
[JsonSerializable(typeof(AppCatalogEntry))]
[JsonSerializable(typeof(AppCatalogResponse))]
[JsonSerializable(typeof(List<AppCatalogEntry>))]
[JsonSerializable(typeof(AppInstallRequest))]
[JsonSerializable(typeof(AppInstallResponse))]
[JsonSerializable(typeof(AppCodeSessionResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Panel.OpenUrlRequest))]
// Widgets - settings
[JsonSerializable(typeof(WidgetSettingsDocument))]
[JsonSerializable(typeof(WidgetSettingsPatch))]
[JsonSerializable(typeof(Dictionary<string, System.Text.Json.JsonElement>))]
// Widgets - proxy
[JsonSerializable(typeof(AppProxyRequest))]
[JsonSerializable(typeof(AppProxyResponse))]
[JsonSerializable(typeof(AppDispatchRequest))]
[JsonSerializable(typeof(AppDispatchResponse))]
[JsonSerializable(typeof(AppInstallStatusDto))]
[JsonSerializable(typeof(AppInstallTriggerDto))]

// OTA self-update routes + GitHub provider DTOs
[JsonSerializable(typeof(UpdateStatusResponse))]
[JsonSerializable(typeof(UpdateProgressResponse))]
[JsonSerializable(typeof(UpdateStartResponse))]
[JsonSerializable(typeof(UpdateStartRequest))]
[JsonSerializable(typeof(UpdateStatusChangedFrame))]
[JsonSerializable(typeof(GitHubRelease))]
[JsonSerializable(typeof(List<GitHubRelease>))]
[JsonSerializable(typeof(GitHubReleaseAsset))]
[JsonSerializable(typeof(List<GitHubReleaseAsset>))]
[JsonSerializable(typeof(Nexus.Service.Persistence.UpdateSettings))]
[JsonSerializable(typeof(Nexus.Service.Persistence.UpdatePrefs))]
[JsonSerializable(typeof(Nexus.Service.Persistence.UpdatePrefsPatch))]
[JsonSerializable(typeof(Nexus.Service.Update.StagedInstallMarker))]

// Conflict warning system - sidebar alarm for competing third-party apps.
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.DetectedConflict))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Conflicts.DetectedConflict>))]
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.GetConflictsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.KillConflictBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.KillConflictResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Conflicts.ConflictsFrame))]

// Install-time defaults table - read once on startup from the embedded
// data/install-defaults.json resource. Nested POCOs are picked up
// transitively by the source generator.
[JsonSerializable(typeof(Nexus.Service.Defaults.InstallDefaultsDocument))]

// Fleet telemetry heartbeat payload (anonymous).
[JsonSerializable(typeof(Nexus.Service.Telemetry.HeartbeatPayload))]

// Phone-as-webcam control surface.
[JsonSerializable(typeof(Nexus.Service.Models.Webcam.WebcamStartRequest))]
[JsonSerializable(typeof(Nexus.Service.Models.Webcam.WebcamStatusResponse))]

// Home Assistant integration.
[JsonSerializable(typeof(HaEntityDto))]
[JsonSerializable(typeof(List<HaEntityDto>))]
[JsonSerializable(typeof(HaConfigResponse))]
[JsonSerializable(typeof(HaConfigBody))]
[JsonSerializable(typeof(HaConfigSetResponse))]
[JsonSerializable(typeof(HaEntitiesResponse))]
[JsonSerializable(typeof(HaSetEntityBody))]
[JsonSerializable(typeof(HomeAssistantChangedFrame))]

// Lian Li Uni Hub SL-Infinity.
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiFanCountRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiCompositionResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiCompositionRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiLightingResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiLightingRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiModeInfoDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiModeInfoDto[]))]
// Lian Li L-Wireless (SLV3) dongle: discovery + bind/unbind/identify.
[JsonSerializable(typeof(Nexus.Service.Peripherals.LianLiWireless.Slv3State))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.LianLiWireless.Slv3FanInfo))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.LianLiWireless.Slv3FanInfo[]))]
[JsonSerializable(typeof(Nexus.Service.Routes.Slv3MacRequest))]
// Lian Li L-Wireless SL-LCD fan screens: discovery/settings, content, media library.
[JsonSerializable(typeof(Nexus.Service.Peripherals.LianLiWireless.Slv3LcdMediaItem))]
[JsonSerializable(typeof(Nexus.Service.Routes.Slv3LcdScreenDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.Slv3LcdScreensResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Slv3LcdSettingsRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.Slv3LcdContentRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.Slv3LcdMediaDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.Slv3LcdMediaListResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Slv3LcdImportResponse))]
// Lian Li Uni Fan TL hub.
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiTlStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiTlFanDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.LianLiTlFanDto[]))]
// Lian Li Galahad II Trinity AIO.
[JsonSerializable(typeof(Nexus.Service.Routes.Galahad2StateResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Galahad2LightingResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.Galahad2LightingRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.Galahad2ModeInfoDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.Galahad2ModeInfoDto[]))]
// Corsair iCUE LINK System Hub.
[JsonSerializable(typeof(Nexus.Service.Routes.CorsairStateResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.CorsairDeviceDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.CorsairDeviceDto[]))]
// Corsair iCUE LINK LCD.
[JsonSerializable(typeof(Nexus.Service.Peripherals.CorsairLink.LcdMediaItem))]
[JsonSerializable(typeof(Nexus.Service.Peripherals.CorsairLink.LcdMediaItem[]))]
[JsonSerializable(typeof(Nexus.Service.Routes.LcdMediaListResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.LcdUploadResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.LcdSettingsRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.LcdStateResponse))]
[JsonSerializable(typeof(int[]))]
[JsonSerializable(typeof(bool[]))]
// Lian Li Strimer Plus.
[JsonSerializable(typeof(Nexus.Service.Routes.StrimerLightingResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.StrimerLightingRequest))]
[JsonSerializable(typeof(Nexus.Service.Routes.StrimerModeInfoDto))]
[JsonSerializable(typeof(Nexus.Service.Routes.StrimerModeInfoDto[]))]

// Diagnostics app: aggregated health + per-domain detail + bundle export.
[JsonSerializable(typeof(Nexus.Service.Diagnostics.DiagnosticsHealthResponse))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.HealthComponent))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.HealthComponentReason))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.EventLog.DiagnosticIncident))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.EventLog.DiagnosticAppInfo))]
[JsonSerializable(typeof(Nexus.Service.Routes.IncidentsResponse))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Storage.SmartSnapshot))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Storage.SmartDriveInfo))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Storage.SmartAttributeWire))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Storage.SmartNvmeWire))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Gpu.GpuThrottleInfo))]
[JsonSerializable(typeof(Nexus.Service.Routes.GpuInfoWire))]
[JsonSerializable(typeof(Nexus.Service.Routes.GpuHealthResponse))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Cooling.CoolingStallSnapshot))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Cooling.CoolingStallDevice))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Memory.MemoryModuleInfo))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Memory.MemoryTestResult))]
[JsonSerializable(typeof(Nexus.Service.Routes.MemoryHealthResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.MemoryTestScheduleResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.MemoryTestCancelResponse))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.SystemInfo.PnpProblemDevice))]
[JsonSerializable(typeof(Nexus.Service.Routes.SystemDiagnosticsCounts))]
[JsonSerializable(typeof(Nexus.Service.Routes.SystemDiagnosticsResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.EventLogClearResponse))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Temperature.TemperaturePoint))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Temperature.TemperatureEpisode))]
[JsonSerializable(typeof(Nexus.Service.Routes.TemperatureSeriesWire))]
[JsonSerializable(typeof(Nexus.Service.Routes.TemperatureHistoryResponse))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Temperature.TemperatureAppSlice))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Temperature.TemperatureAppBucket))]
[JsonSerializable(typeof(Nexus.Service.Diagnostics.Temperature.TemperatureAppUsageResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.OpenEventViewerResponse))]
[JsonSerializable(typeof(Nexus.Service.Routes.OpenDeviceManagerResponse))]

// Stream Deck
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckSummaryDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckSummaryDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.GetStreamDecksResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.UpdateStreamDeckBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckConfigEnvelope))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckImageUploadResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckChangedFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckTileFrame))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckPendingEditDto))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckPendingEditResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckSimPressBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckSimulateBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckNavBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckDevModelDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckDevModelDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.StreamDeckDevModelsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.DeckPresetDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Peripherals.StreamDeck.DeckPresetDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.GetDeckPresetsResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.CreateDeckPresetBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.CreateDeckPresetResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.UpdateDeckPresetBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.SetActiveDeckPresetBody))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.DeleteDeckPresetResponse))]
// Stream Deck binding model - the shared DeckAction/DeckConfig tree that
// rides the GET/PUT config wire contract (see Nexus.Service.Deck.DeckActionModel).
[JsonSerializable(typeof(Nexus.Service.Deck.DeckConfig))]
[JsonSerializable(typeof(Nexus.Service.Deck.DeckFolder))]
[JsonSerializable(typeof(Nexus.Service.Deck.DeckSlot))]
[JsonSerializable(typeof(List<Nexus.Service.Deck.DeckSlot>))]
[JsonSerializable(typeof(Nexus.Service.Deck.DeckIcon))]
[JsonSerializable(typeof(Nexus.Service.Deck.DeckTitleStyle))]
[JsonSerializable(typeof(Nexus.Service.Deck.DeckAction))]
[JsonSerializable(typeof(Nexus.Service.Deck.DeckSystemAction))]
[JsonSerializable(typeof(Nexus.Service.Deck.DeckNexusAction))]
[JsonSerializable(typeof(Nexus.Service.Deck.DeckToggleState))]
[JsonSerializable(typeof(Nexus.Service.Deck.DeckSequenceStep))]
[JsonSerializable(typeof(List<Nexus.Service.Deck.DeckSequenceStep>))]
// Deck key icon image store (POST/GET /deck/images)
[JsonSerializable(typeof(Nexus.Service.Models.Deck.DeckImageUploadResponse))]
// Elgato Stream Deck profile import
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.ElgatoProfileSummaryDto))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Peripherals.StreamDeck.ElgatoProfileSummaryDto>))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.ElgatoProfilesResponse))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.ElgatoUnmappedEntry))]
[JsonSerializable(typeof(List<Nexus.Service.Models.Peripherals.StreamDeck.ElgatoUnmappedEntry>))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.ElgatoImportReport))]
[JsonSerializable(typeof(Nexus.Service.Models.Peripherals.StreamDeck.ImportElgatoProfileResponse))]

// Metadata-only: skips the per-type generated fast-path writer, a large AOT
// code cost across this context's roots; serialization runs through the
// shared metadata-driven writer instead. Deserialization is metadata-driven
// in both modes, and the HTTP pipeline's merged options already disabled the
// fast path, so only typed JsonTypeInfo writes change code path.
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Metadata)]
public partial class AppJsonContext : JsonSerializerContext;
