using System.Numerics;
using System.Text.Json;
using Nexus.Service.Lighting.Scene;
using Nexus.Service.Persistence;

namespace Nexus.Service.Tests.Lighting.Scene;

public class SceneMathTests
{
    private static Vector3 V(JsonElement e) => new(e[0].GetSingle(), e[1].GetSingle(), e[2].GetSingle());

    [Fact]
    public void Projection_matches_threejs_vectors()
    {
        // Generated by three.js in nexus-web; the web editor draws the scene with that camera.
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "scene-projection-vectors.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        var w = doc.RootElement.GetProperty("canvas")[0].GetSingle();
        var h = doc.RootElement.GetProperty("canvas")[1].GetSingle();
        var checkedPoints = 0;
        foreach (var c in doc.RootElement.GetProperty("cases").EnumerateArray())
        {
            var cam = c.GetProperty("camera");
            var basis = new SceneCameraBasis(V(cam.GetProperty("position")), V(cam.GetProperty("target")), cam.GetProperty("fov").GetSingle(), w, h);
            var points = c.GetProperty("points");
            var expected = c.GetProperty("expected");
            for (var i = 0; i < points.GetArrayLength(); i++)
            {
                var visible = basis.Project(V(points[i]), out var x, out var y);
                if (expected[i].ValueKind == JsonValueKind.Null)
                {
                    Assert.False(visible);
                    continue;
                }
                Assert.True(visible);
                Assert.InRange(x, expected[i][0].GetSingle() - 0.05f, expected[i][0].GetSingle() + 0.05f);
                Assert.InRange(y, expected[i][1].GetSingle() - 0.05f, expected[i][1].GetSingle() + 0.05f);
                checkedPoints++;
            }
        }
        Assert.True(checkedPoints > 20);
    }

    [Fact]
    public void Yaw_turns_counter_clockwise_seen_from_above()
    {
        var turned = SceneMath.RotateYaw(new Vector3(1, 0, 0), 90);
        Assert.Equal(0f, turned.X, 4);
        Assert.Equal(-1f, turned.Z, 4);
    }

    [Fact]
    public void Anchor_quad_places_the_map_top_left_at_the_surface_top_left()
    {
        var obj = new SceneObject { Id = "kb", Position = [100, 0, 50], Yaw = 0 };
        // A keyboard top: right along +X, map top toward the far edge (-Z).
        var anchor = new SceneAnchor { Id = "top", Center = [0, 30, 0], Right = [1, 0, 0], Up = [0, 0, -1], Width = 440, Height = 140 };
        var quad = SceneMath.AnchorQuad(obj, anchor, 0, false);

        var topLeft = quad.At(0, 0);
        Assert.Equal(new Vector3(100 - 220, 30, 50 - 70), topLeft);
        var bottomRight = quad.At(1, 1);
        Assert.Equal(new Vector3(100 + 220, 30, 50 + 70), bottomRight);
    }

    [Fact]
    public void Quarter_turn_swaps_the_axes_and_keeps_the_surface_filled()
    {
        var obj = new SceneObject { Id = "o" };
        var anchor = new SceneAnchor { Id = "a", Center = [0, 0, 0], Right = [1, 0, 0], Up = [0, 1, 0], Width = 200, Height = 100 };
        var quad = SceneMath.AnchorQuad(obj, anchor, 90, false);

        // Map u now runs down the surface; the turned map spans the surface's height along u.
        Assert.Equal(new Vector3(0, -100, 0), quad.AxisU);
        Assert.Equal(new Vector3(-200, 0, 0), quad.AxisV);
    }

    [Fact]
    public void Placements_skip_bindings_whose_targets_all_miss_and_keep_target_order()
    {
        var doc = new LightingSceneDoc
        {
            Objects =
            {
                new SceneObject
                {
                    Id = "case",
                    Anchors =
                    {
                        new SceneAnchor { Id = "f1", Center = [-100, 0, 0] },
                        new SceneAnchor { Id = "f2", Center = [100, 0, 0] },
                    },
                },
            },
            Bindings =
            {
                new SceneBinding { DeviceId = "chain", Targets = { new() { ObjectId = "case", AnchorId = "f2" }, new() { ObjectId = "case", AnchorId = "f1" } } },
                new SceneBinding { DeviceId = "gone", Targets = { new() { ObjectId = "case", AnchorId = "nope" } } },
            },
        };
        var placements = SceneMath.Placements(doc);

        Assert.False(placements.ContainsKey("gone"));
        Assert.Equal(100f, placements["chain"][0].Center.X);
        Assert.Equal(-100f, placements["chain"][1].Center.X);
    }

    [Fact]
    public void Camera_is_null_while_the_view_is_off_or_has_no_camera()
    {
        Assert.Null(SceneMath.Camera(new SceneView { Enabled = false, Camera = new SceneCamera() }, 1000, 600));
        Assert.Null(SceneMath.Camera(new SceneView { Enabled = true }, 1000, 600));
        Assert.NotNull(SceneMath.Camera(new SceneView { Enabled = true, Camera = new SceneCamera { Position = [0, 0, 10] } }, 1000, 600));
    }
}
