using System.Collections.Generic;

namespace Qos.Service.Peripherals.Keeb.Hid.Layout
{
    public static class KeebLayoutTables
    {
        #region Keeb ANSI
        public static readonly List<KeebLayoutModel> ANSILayout =
        [
            //Row 1
            new KeebLayoutModel(Keyboard.TopLED1, null, new LedPosition(0, 1, 136), null),
            new KeebLayoutModel(Keyboard.TopLED2, null, new LedPosition(0, 2 , 135), null),
            new KeebLayoutModel(Keyboard.TopLED3, null, new LedPosition(0, 3 , 134), null),
            new KeebLayoutModel(Keyboard.TopLED4, null, new LedPosition(0, 4 , 133), null),
            new KeebLayoutModel(Keyboard.TopLED5, null, new LedPosition(0, 5 , 132), null),
            new KeebLayoutModel(Keyboard.TopLED6, null, new LedPosition(0, 6 , 131), null),
            new KeebLayoutModel(Keyboard.TopLED7, null, new LedPosition(0, 7 , 130), null),
            new KeebLayoutModel(Keyboard.TopLED8, null, new LedPosition(0, 8 , 129), null),
            new KeebLayoutModel(Keyboard.TopLED9, null, new LedPosition(0, 9 , 128), null),
            new KeebLayoutModel(Keyboard.TopLED10, null, new LedPosition(0, 10, 127), null),
            new KeebLayoutModel(Keyboard.TopLED11, null, new LedPosition(0, 11, 176), null),
            new KeebLayoutModel(Keyboard.TopLED12, null, new LedPosition(0, 12, 175), null),
            new KeebLayoutModel(Keyboard.TopLED13, null, new LedPosition(0, 13, 174), null),
            new KeebLayoutModel(Keyboard.TopLED14, null, new LedPosition(0, 14, 173), null),
            new KeebLayoutModel(Keyboard.TopLED15, null, new LedPosition(0, 15, 172), null),
            new KeebLayoutModel(Keyboard.TopLED16, null, new LedPosition(0, 16, 171), null),
            new KeebLayoutModel(Keyboard.TopLED17, null, new LedPosition(0, 17, 170), null),
            new KeebLayoutModel(Keyboard.TopLED18, null, new LedPosition(0, 18, 169), null),
            new KeebLayoutModel(Keyboard.TopLED19, null, new LedPosition(0, 19, 168), null),
            //Row 2
            new KeebLayoutModel(Keyboard.ScrollWheel, null, new LedPosition(1, 2 , 177), null),
            //Row 3
            new KeebLayoutModel(Keyboard.MediaLED1, new MatrixPosition(3, 14) , new LedPosition(2, 1, 78), new MatrixPosition(1, 0)),
            new KeebLayoutModel(Keyboard.MediaLED2, new MatrixPosition(3, 15), new LedPosition(2, 2, 79), new MatrixPosition(1, 1)),
            new KeebLayoutModel(Keyboard.MediaLED3,  new MatrixPosition(3, 16), new LedPosition(2, 3, 80), new MatrixPosition(1, 2)),
            new KeebLayoutModel(Keyboard.MediaLED4,  new MatrixPosition(4, 14), new LedPosition(2, 4, 99), new MatrixPosition(1, 3)),
            new KeebLayoutModel(Keyboard.MediaLED5,  new MatrixPosition(4, 16), new LedPosition(2, 5, 101), new MatrixPosition(1, 4)),
            //Row 4
            new KeebLayoutModel(Keyboard.LeftLED1,     null, new LedPosition(3, 0 , 137), null),
            new KeebLayoutModel(Keyboard.ESC,          new MatrixPosition(0,0), new LedPosition(3, 1 , 1),  new MatrixPosition(2, 0)),
            new KeebLayoutModel(Keyboard.F1,           new MatrixPosition(0,2), new LedPosition(3, 3 , 3),  new MatrixPosition(2, 1)),
            new KeebLayoutModel(Keyboard.F2,           new MatrixPosition(0,3), new LedPosition(3, 4 , 4),  new MatrixPosition(2, 2)),
            new KeebLayoutModel(Keyboard.F3,           new MatrixPosition(0,4), new LedPosition(3, 5 , 5),  new MatrixPosition(2, 3)),
            new KeebLayoutModel(Keyboard.F4,           new MatrixPosition(0,5), new LedPosition(3, 6 , 6),  new MatrixPosition(2, 4)),
            new KeebLayoutModel(Keyboard.F5,           new MatrixPosition(0,6), new LedPosition(3, 8, 7),   new MatrixPosition(2, 5)),
            new KeebLayoutModel(Keyboard.F6,           new MatrixPosition(0,7), new LedPosition(3, 9, 8),   new MatrixPosition(2, 6)),
            new KeebLayoutModel(Keyboard.F7,           new MatrixPosition(0,8), new LedPosition(3, 10, 9),  new MatrixPosition(2, 7)),
            new KeebLayoutModel(Keyboard.F8,           new MatrixPosition(0,9), new LedPosition(3, 11, 10), new MatrixPosition(2, 8)),
            new KeebLayoutModel(Keyboard.F9,           new MatrixPosition(0,10), new LedPosition(3, 13, 11), new MatrixPosition(2, 9)),
            new KeebLayoutModel(Keyboard.F10,          new MatrixPosition(0,11), new LedPosition(3, 14, 12), new MatrixPosition(2, 10)),
            new KeebLayoutModel(Keyboard.F11,          new MatrixPosition(0,12), new LedPosition(3, 15, 13), new MatrixPosition(2, 11)),
            new KeebLayoutModel(Keyboard.F12,          new MatrixPosition(0,13), new LedPosition(3, 16, 14), new MatrixPosition(2, 12)),
            new KeebLayoutModel(Keyboard.Pause,        new MatrixPosition(0,14), new LedPosition(3, 17, 15), new MatrixPosition(2, 13)),
            new KeebLayoutModel(Keyboard.ScrLk,        new MatrixPosition(0,15), new LedPosition(3, 18, 16), new MatrixPosition(2, 14)),
            new KeebLayoutModel(Keyboard.PrnSrc,       new MatrixPosition(0,16), new LedPosition(3, 19, 17), new MatrixPosition(2, 15)),
            new KeebLayoutModel(Keyboard.RightLED1,    null, new LedPosition(3, 20, 167), null),
            //Row 5
            new KeebLayoutModel(Keyboard.LeftLED2,       null, new LedPosition(4, 0 , 138), null),
            new KeebLayoutModel(Keyboard.Tilde,          new MatrixPosition(1,0), new LedPosition(4, 1 , 22), new MatrixPosition(3, 0)),
            new KeebLayoutModel(Keyboard.One,            new MatrixPosition(1,1), new LedPosition(4, 2 , 23), new MatrixPosition(3, 1)),
            new KeebLayoutModel(Keyboard.Two,            new MatrixPosition(1,2), new LedPosition(4, 3 , 24), new MatrixPosition(3, 2)),
            new KeebLayoutModel(Keyboard.Three,          new MatrixPosition(1,3), new LedPosition(4, 4 , 25), new MatrixPosition(3, 3)),
            new KeebLayoutModel(Keyboard.Four,           new MatrixPosition(1,4), new LedPosition(4, 5, 26), new MatrixPosition(3, 4)),
            new KeebLayoutModel(Keyboard.Five,           new MatrixPosition(1,5), new LedPosition(4, 6, 27), new MatrixPosition(3, 5)),
            new KeebLayoutModel(Keyboard.Six,            new MatrixPosition(1,6), new LedPosition(4, 7, 28), new MatrixPosition(3, 6)),
            new KeebLayoutModel(Keyboard.Seven,          new MatrixPosition(1,7), new LedPosition(4, 8, 29), new MatrixPosition(3, 7)),
            new KeebLayoutModel(Keyboard.Eight,          new MatrixPosition(1,8), new LedPosition(4, 9, 30), new MatrixPosition(3, 8)),
            new KeebLayoutModel(Keyboard.Nine,           new MatrixPosition(1,9), new LedPosition(4, 10, 31), new MatrixPosition(3, 9)),
            new KeebLayoutModel(Keyboard.Zero,           new MatrixPosition(1,10), new LedPosition(4, 11, 32), new MatrixPosition(3, 10)),
            new KeebLayoutModel(Keyboard.Hyphen,         new MatrixPosition(1,11), new LedPosition(4, 12, 33), new MatrixPosition(3, 11)),
            new KeebLayoutModel(Keyboard.Plus,           new MatrixPosition(1,12), new LedPosition(4, 13, 34), new MatrixPosition(3, 12)),
            new KeebLayoutModel(Keyboard.BackSpace,      new MatrixPosition(1,13), new LedPosition(4, 15, 35), new MatrixPosition(3, 13)),
            new KeebLayoutModel(Keyboard.Insert,         new MatrixPosition(1,14), new LedPosition(4, 17, 36), new MatrixPosition(3, 14)),
            new KeebLayoutModel(Keyboard.HOME,           new MatrixPosition(1,15), new LedPosition(4, 18, 37), new MatrixPosition(3, 15)),
            new KeebLayoutModel(Keyboard.PAGEUp,         new MatrixPosition(1,16), new LedPosition(4, 19, 38), new MatrixPosition(3, 16)),
            new KeebLayoutModel(Keyboard.RightLED2,      null, new LedPosition(4, 20, 166), null),
            //Row 6
            new KeebLayoutModel(Keyboard.LeftLED3,     null, new LedPosition(5, 0 , 139), null),
            new KeebLayoutModel(Keyboard.Tab,          new MatrixPosition(2,0), new LedPosition(5, 1 , 43), new MatrixPosition(4, 0)),
            new KeebLayoutModel(Keyboard.Q,            new MatrixPosition(2,1), new LedPosition(5, 3 , 44), new MatrixPosition(4, 1)),
            new KeebLayoutModel(Keyboard.W,            new MatrixPosition(2,2), new LedPosition(5, 4 , 45), new MatrixPosition(4, 2)),
            new KeebLayoutModel(Keyboard.E,            new MatrixPosition(2,3), new LedPosition(5, 5 , 46), new MatrixPosition(4, 3)),
            new KeebLayoutModel(Keyboard.R,            new MatrixPosition(2,4), new LedPosition(5, 6, 47), new MatrixPosition(4, 4)),
            new KeebLayoutModel(Keyboard.T,            new MatrixPosition(2,5), new LedPosition(5, 7, 48), new MatrixPosition(4, 5)),
            new KeebLayoutModel(Keyboard.Y,            new MatrixPosition(2,6), new LedPosition(5, 8, 49), new MatrixPosition(4, 6)),
            new KeebLayoutModel(Keyboard.U,            new MatrixPosition(2,7), new LedPosition(5, 9, 50), new MatrixPosition(4, 7)),
            new KeebLayoutModel(Keyboard.I,            new MatrixPosition(2,8), new LedPosition(5, 10, 51), new MatrixPosition(4, 8)),
            new KeebLayoutModel(Keyboard.O,            new MatrixPosition(2,9), new LedPosition(5, 11, 52), new MatrixPosition(4, 9)),
            new KeebLayoutModel(Keyboard.P,            new MatrixPosition(2,10), new LedPosition(5, 12, 53), new MatrixPosition(4, 10)),
            new KeebLayoutModel(Keyboard.LeftBracket,  new MatrixPosition(2,11), new LedPosition(5, 13, 54), new MatrixPosition(4, 11)),
            new KeebLayoutModel(Keyboard.RightBracket, new MatrixPosition(2,12), new LedPosition(5, 14, 55), new MatrixPosition(4, 12)),
            new KeebLayoutModel(Keyboard.BackSlash,    new MatrixPosition(2,13), new LedPosition(5, 15, 56), new MatrixPosition(4, 13)),
            new KeebLayoutModel(Keyboard.DELETE,       new MatrixPosition(2,14), new LedPosition(5, 17, 57), new MatrixPosition(4, 14)),
            new KeebLayoutModel(Keyboard.END,          new MatrixPosition(2,15), new LedPosition(5, 18, 58), new MatrixPosition(4, 15)),
            new KeebLayoutModel(Keyboard.PAGEDown,     new MatrixPosition(2,16), new LedPosition(5, 19, 59), new MatrixPosition(4, 16)),
            new KeebLayoutModel(Keyboard.RightLED3,    null, new LedPosition(5, 20, 165), null),
            //Row 8
            new KeebLayoutModel(Keyboard.LeftLED4,     null, new LedPosition(6, 0 , 140), null),
            new KeebLayoutModel(Keyboard.CapLock,      new MatrixPosition(3,0), new LedPosition(6, 1 , 64), new MatrixPosition(5, 0)),
            new KeebLayoutModel(Keyboard.A,            new MatrixPosition(3,1), new LedPosition(6, 3 , 65), new MatrixPosition(5, 1)),
            new KeebLayoutModel(Keyboard.S,            new MatrixPosition(3,2), new LedPosition(6, 4 , 66), new MatrixPosition(5, 2)),
            new KeebLayoutModel(Keyboard.D,            new MatrixPosition(3,3), new LedPosition(6, 5, 67), new MatrixPosition(5, 3)),
            new KeebLayoutModel(Keyboard.F,            new MatrixPosition(3,4), new LedPosition(6, 6, 68), new MatrixPosition(5, 4)),
            new KeebLayoutModel(Keyboard.G,            new MatrixPosition(3,5), new LedPosition(6, 7, 69), new MatrixPosition(5, 5)),
            new KeebLayoutModel(Keyboard.H,            new MatrixPosition(3,6), new LedPosition(6, 8, 70), new MatrixPosition(5, 6)),
            new KeebLayoutModel(Keyboard.J,            new MatrixPosition(3,7), new LedPosition(6, 9, 71), new MatrixPosition(5, 7)),
            new KeebLayoutModel(Keyboard.K,            new MatrixPosition(3,8), new LedPosition(6, 10, 72), new MatrixPosition(5, 8)),
            new KeebLayoutModel(Keyboard.L,            new MatrixPosition(3,9), new LedPosition(6, 11, 73), new MatrixPosition(5, 9)),
            new KeebLayoutModel(Keyboard.Semicolon,    new MatrixPosition(3,10), new LedPosition(6, 12, 74), new MatrixPosition(5, 10)),
            new KeebLayoutModel(Keyboard.SingleQuote,  new MatrixPosition(3,11), new LedPosition(6, 13, 75), new MatrixPosition(5, 11)),
            new KeebLayoutModel(Keyboard.Enter,        new MatrixPosition(3,13), new LedPosition(6, 15, 77), new MatrixPosition(5, 12)),
            new KeebLayoutModel(Keyboard.RightLED4,    null, new LedPosition(6, 20, 164), null),
            //Row 10
            new KeebLayoutModel(Keyboard.LeftLED5,     null, new LedPosition(7, 0 , 141), null),
            new KeebLayoutModel(Keyboard.LeftShift,    new MatrixPosition(4,0), new LedPosition(7, 2 , 85), new MatrixPosition(6, 0)),
            new KeebLayoutModel(Keyboard.Z,            new MatrixPosition(4,2), new LedPosition(7, 4 , 87), new MatrixPosition(6, 1)),
            new KeebLayoutModel(Keyboard.X,            new MatrixPosition(4,3), new LedPosition(7, 5 , 88), new MatrixPosition(6, 2)),
            new KeebLayoutModel(Keyboard.C,            new MatrixPosition(4,4), new LedPosition(7, 6, 89), new MatrixPosition(6, 3)),
            new KeebLayoutModel(Keyboard.V,            new MatrixPosition(4,5), new LedPosition(7, 7, 90), new MatrixPosition(6, 4)),
            new KeebLayoutModel(Keyboard.B,            new MatrixPosition(4,6), new LedPosition(7, 8, 91), new MatrixPosition(6, 5)),
            new KeebLayoutModel(Keyboard.N,            new MatrixPosition(4,7), new LedPosition(7, 9, 92), new MatrixPosition(6, 6)),
            new KeebLayoutModel(Keyboard.M,            new MatrixPosition(4,8), new LedPosition(7, 10, 93), new MatrixPosition(6, 7)),
            new KeebLayoutModel(Keyboard.Comma,        new MatrixPosition(4,9), new LedPosition(7, 11, 94), new MatrixPosition(6, 8)),
            new KeebLayoutModel(Keyboard.Period,       new MatrixPosition(4,10), new LedPosition(7, 12, 95), new MatrixPosition(6, 9)),
            new KeebLayoutModel(Keyboard.Slash,        new MatrixPosition(4,11), new LedPosition(7, 13, 96), new MatrixPosition(6, 10)),
            new KeebLayoutModel(Keyboard.RightShift,   new MatrixPosition(4,13), new LedPosition(7, 15, 98), new MatrixPosition(6, 11)),
            new KeebLayoutModel(Keyboard.UP,           new MatrixPosition(4,15), new LedPosition(7, 18, 100), new MatrixPosition(6, 12)),
            new KeebLayoutModel(Keyboard.RightLED5,    null, new LedPosition(7, 20, 163), null),
            //Row 12
            new KeebLayoutModel(Keyboard.LeftLED6,     null, new LedPosition(8, 0 , 142), null),
            new KeebLayoutModel(Keyboard.CTRL_L,       new MatrixPosition(5,0), new LedPosition(8, 1, 106), new MatrixPosition(7, 0)),
            new KeebLayoutModel(Keyboard.WIN_L,        new MatrixPosition(5,1), new LedPosition(8, 2, 107), new MatrixPosition(7, 1)),
            new KeebLayoutModel(Keyboard.ALT_L,        new MatrixPosition(5,2), new LedPosition(8, 3, 108), new MatrixPosition(7, 2)),
            new KeebLayoutModel(Keyboard.SPACE_LL,     null, new LedPosition(8, 5, 110), null),
            new KeebLayoutModel(Keyboard.SPACE_L,      null, new LedPosition(8, 6, 111), null),
            new KeebLayoutModel(Keyboard.SPACE,        new MatrixPosition(5,6), new LedPosition(8, 7, 112), new MatrixPosition(7, 3)),
            new KeebLayoutModel(Keyboard.SPACE_R,      null, new LedPosition(8, 8, 113), null),
            new KeebLayoutModel(Keyboard.SPACE_RR,     null, new LedPosition(8, 9, 114), null),
            new KeebLayoutModel(Keyboard.ALT_R,        new MatrixPosition(5,10), new LedPosition(8, 12, 116), new MatrixPosition(7, 4)),
            new KeebLayoutModel(Keyboard.FN,           new MatrixPosition(5,11), new LedPosition(8, 13, 117), new MatrixPosition(7, 5)),
            new KeebLayoutModel(Keyboard.Menu,         new MatrixPosition(5,12), new LedPosition(8, 14, 118), new MatrixPosition(7, 6)),
            new KeebLayoutModel(Keyboard.CTRL_R,       new MatrixPosition(5,13), new LedPosition(8, 15, 119), new MatrixPosition(7, 7)),
            new KeebLayoutModel(Keyboard.LEFT,         new MatrixPosition(5,14), new LedPosition(8, 17, 120), new MatrixPosition(7, 8)),
            new KeebLayoutModel(Keyboard.DOWN,         new MatrixPosition(5,15), new LedPosition(8, 18, 121), new MatrixPosition(7, 9)),
            new KeebLayoutModel(Keyboard.RIGHT,        new MatrixPosition(5,16), new LedPosition(8, 19, 122), new MatrixPosition(7, 10)),
            new KeebLayoutModel(Keyboard.RightLED6,    null, new LedPosition(8, 20, 162), null),
            //Row 14
            new KeebLayoutModel(Keyboard.BottomLED1,   null, new LedPosition(9, 1, 143), null),
            new KeebLayoutModel(Keyboard.BottomLED2,   null, new LedPosition(9, 2, 144), null),
            new KeebLayoutModel(Keyboard.BottomLED3,   null, new LedPosition(9, 3, 145), null),
            new KeebLayoutModel(Keyboard.BottomLED4,   null, new LedPosition(9, 4, 146), null),
            new KeebLayoutModel(Keyboard.BottomLED5,   null, new LedPosition(9, 5, 147), null),
            new KeebLayoutModel(Keyboard.BottomLED6,   null, new LedPosition(9, 6, 148), null),
            new KeebLayoutModel(Keyboard.BottomLED7,   null, new LedPosition(9, 7, 149), null),
            new KeebLayoutModel(Keyboard.BottomLED8,   null, new LedPosition(9, 8, 150), null),
            new KeebLayoutModel(Keyboard.BottomLED9,   null, new LedPosition(9, 9, 151), null),
            new KeebLayoutModel(Keyboard.BottomLED10,  null, new LedPosition(9, 10, 152), null),
            new KeebLayoutModel(Keyboard.BottomLED11,  null, new LedPosition(9, 11, 153), null),
            new KeebLayoutModel(Keyboard.BottomLED12,  null, new LedPosition(9, 12, 154), null),
            new KeebLayoutModel(Keyboard.BottomLED13,  null, new LedPosition(9, 13, 155), null),
            new KeebLayoutModel(Keyboard.BottomLED14,  null, new LedPosition(9, 14, 156), null),
            new KeebLayoutModel(Keyboard.BottomLED15,  null, new LedPosition(9, 15, 157), null),
            new KeebLayoutModel(Keyboard.BottomLED16,  null, new LedPosition(9, 16, 158), null),
            new KeebLayoutModel(Keyboard.BottomLED17,  null, new LedPosition(9, 17, 159), null),
            new KeebLayoutModel(Keyboard.BottomLED18,  null, new LedPosition(9, 18, 160), null),
            new KeebLayoutModel(Keyboard.BottomLED19,  null, new LedPosition(9, 19, 161), null),
        ];

        public static Dictionary<Keyboard, KeebLayoutModel> BUTTON_KEY_LAYOUT_DICTIONAY => new()
        {
            //Row 1
            { Keyboard.TopLED1, new KeebLayoutModel(Keyboard.TopLED1, null, new LedPosition(0, 1, 136), null)},
            { Keyboard.TopLED2, new KeebLayoutModel(Keyboard.TopLED2, null, new LedPosition(0, 2 , 135), null)},
            { Keyboard.TopLED3, new KeebLayoutModel(Keyboard.TopLED3, null, new LedPosition(0, 3 , 134), null)},
            { Keyboard.TopLED4, new KeebLayoutModel(Keyboard.TopLED4, null, new LedPosition(0, 4 , 133), null)},
            { Keyboard.TopLED5, new KeebLayoutModel(Keyboard.TopLED5, null, new LedPosition(0, 5 , 132), null)},
            { Keyboard.TopLED6,  new KeebLayoutModel(Keyboard.TopLED6, null, new LedPosition(0, 6 , 131), null)},
            { Keyboard.TopLED7,  new KeebLayoutModel(Keyboard.TopLED7, null, new LedPosition(0, 7 , 130), null)},
            { Keyboard.TopLED8,  new KeebLayoutModel(Keyboard.TopLED8, null, new LedPosition(0, 8 , 129), null)},
            { Keyboard.TopLED9, new KeebLayoutModel(Keyboard.TopLED9, null, new LedPosition(0, 9 , 128), null)},
            { Keyboard.TopLED10, new KeebLayoutModel(Keyboard.TopLED10, null, new LedPosition(0, 10, 127), null)},
            { Keyboard.TopLED11, new KeebLayoutModel(Keyboard.TopLED11, null, new LedPosition(0, 11, 176), null)},
            { Keyboard.TopLED12, new KeebLayoutModel(Keyboard.TopLED12, null, new LedPosition(0, 12, 175), null)},
            { Keyboard.TopLED13, new KeebLayoutModel(Keyboard.TopLED13, null, new LedPosition(0, 13, 174), null)},
            { Keyboard.TopLED14, new KeebLayoutModel(Keyboard.TopLED14, null, new LedPosition(0, 14, 173), null)},
            { Keyboard.TopLED15, new KeebLayoutModel(Keyboard.TopLED15, null, new LedPosition(0, 15, 172), null)},
            { Keyboard.TopLED16, new KeebLayoutModel(Keyboard.TopLED16, null, new LedPosition(0, 16, 171), null)},
            { Keyboard.TopLED17,  new KeebLayoutModel(Keyboard.TopLED17, null, new LedPosition(0, 17, 170), null)},
            { Keyboard.TopLED18, new KeebLayoutModel(Keyboard.TopLED18, null, new LedPosition(0, 18, 169), null)},
            { Keyboard.TopLED19, new KeebLayoutModel(Keyboard.TopLED19, null, new LedPosition(0, 19, 168), null)},
            //Row 2
            { Keyboard.ScrollWheel, new KeebLayoutModel(Keyboard.ScrollWheel, null, new LedPosition(1, 2 , 177), null)},
            //Row 3
            { Keyboard.MediaLED1, new KeebLayoutModel(Keyboard.MediaLED1, new MatrixPosition(3, 14) , new LedPosition(2, 1, 78), new MatrixPosition(1, 0))},
            { Keyboard.MediaLED2, new KeebLayoutModel(Keyboard.MediaLED2, new MatrixPosition(3, 15), new LedPosition(2, 2, 79), new MatrixPosition(1, 1))},
            { Keyboard.MediaLED3, new KeebLayoutModel(Keyboard.MediaLED3,  new MatrixPosition(3, 16), new LedPosition(2, 3, 80), new MatrixPosition(1, 2))},
            { Keyboard.MediaLED4, new KeebLayoutModel(Keyboard.MediaLED4,  new MatrixPosition(4, 14), new LedPosition(2, 4, 99), new MatrixPosition(1, 3))},
            { Keyboard.MediaLED5, new KeebLayoutModel(Keyboard.MediaLED5,  new MatrixPosition(4, 16), new LedPosition(2, 5, 101), new MatrixPosition(1, 4))},
            //Row 4
            { Keyboard.ESC, new KeebLayoutModel(Keyboard.ESC, new MatrixPosition(0, 0), new LedPosition(3, 1, 1), new MatrixPosition(2, 0)) },
            { Keyboard.F1, new KeebLayoutModel(Keyboard.F1, new MatrixPosition(0, 2), new LedPosition(3, 3, 3), new MatrixPosition(2, 1)) },
            { Keyboard.F2, new KeebLayoutModel(Keyboard.F2, new MatrixPosition(0, 3), new LedPosition(3, 4, 4), new MatrixPosition(2, 2)) },
            { Keyboard.F3, new KeebLayoutModel(Keyboard.F3, new MatrixPosition(0, 4), new LedPosition(3, 5, 5), new MatrixPosition(2, 3)) },
            { Keyboard.F4, new KeebLayoutModel(Keyboard.F4, new MatrixPosition(0, 5), new LedPosition(3, 6, 6), new MatrixPosition(2, 4)) },
            { Keyboard.F5, new KeebLayoutModel(Keyboard.F5, new MatrixPosition(0, 6), new LedPosition(3, 8, 7), new MatrixPosition(2, 5)) },
            { Keyboard.F6, new KeebLayoutModel(Keyboard.F6, new MatrixPosition(0, 7), new LedPosition(3, 9, 8), new MatrixPosition(2, 6)) },
            { Keyboard.F7, new KeebLayoutModel(Keyboard.F7, new MatrixPosition(0, 8), new LedPosition(3, 10, 9), new MatrixPosition(2, 7)) },
            { Keyboard.F8, new KeebLayoutModel(Keyboard.F8, new MatrixPosition(0, 9), new LedPosition(3, 11, 10), new MatrixPosition(2, 8)) },
            { Keyboard.F9, new KeebLayoutModel(Keyboard.F9, new MatrixPosition(0, 10), new LedPosition(3, 13, 11), new MatrixPosition(2, 9)) },
            { Keyboard.F10, new KeebLayoutModel(Keyboard.F10, new MatrixPosition(0, 11), new LedPosition(3, 14, 12), new MatrixPosition(2, 10)) },
            { Keyboard.F11, new KeebLayoutModel(Keyboard.F11, new MatrixPosition(0, 12), new LedPosition(3, 15, 13), new MatrixPosition(2, 11)) },
            { Keyboard.F12, new KeebLayoutModel(Keyboard.F12, new MatrixPosition(0, 13), new LedPosition(3, 16, 14), new MatrixPosition(2, 12)) },
            { Keyboard.Pause, new KeebLayoutModel(Keyboard.Pause, new MatrixPosition(0, 14), new LedPosition(3, 17, 15), new MatrixPosition(2, 13)) },
            { Keyboard.ScrLk, new KeebLayoutModel(Keyboard.ScrLk, new MatrixPosition(0, 15), new LedPosition(3, 18, 16), new MatrixPosition(2, 14)) },
            { Keyboard.PrnSrc, new KeebLayoutModel(Keyboard.PrnSrc, new MatrixPosition(0, 16), new LedPosition(3, 19, 17), new MatrixPosition(2, 15)) },
            //Row 5
            { Keyboard.Tilde, new KeebLayoutModel(Keyboard.Tilde, new MatrixPosition(1, 0), new LedPosition(4, 1, 22), new MatrixPosition(3, 0)) },
            { Keyboard.One, new KeebLayoutModel(Keyboard.One, new MatrixPosition(1, 1), new LedPosition(4, 2, 23), new MatrixPosition(3, 1)) },
            { Keyboard.Two, new KeebLayoutModel(Keyboard.Two, new MatrixPosition(1, 2), new LedPosition(4, 3, 24), new MatrixPosition(3, 2)) },
            { Keyboard.Three, new KeebLayoutModel(Keyboard.Three, new MatrixPosition(1, 3), new LedPosition(4, 4, 25), new MatrixPosition(3, 3)) },
            { Keyboard.Four, new KeebLayoutModel(Keyboard.Four, new MatrixPosition(1, 4), new LedPosition(4, 5, 26), new MatrixPosition(3, 4)) },
            { Keyboard.Five, new KeebLayoutModel(Keyboard.Five, new MatrixPosition(1, 5), new LedPosition(4, 6, 27), new MatrixPosition(3, 5)) },
            { Keyboard.Six, new KeebLayoutModel(Keyboard.Six, new MatrixPosition(1, 6), new LedPosition(4, 7, 28), new MatrixPosition(3, 6)) },
            { Keyboard.Seven, new KeebLayoutModel(Keyboard.Seven, new MatrixPosition(1, 7), new LedPosition(4, 8, 29), new MatrixPosition(3, 7)) },
            { Keyboard.Eight, new KeebLayoutModel(Keyboard.Eight, new MatrixPosition(1, 8), new LedPosition(4, 9, 30), new MatrixPosition(3, 8)) },
            { Keyboard.Nine, new KeebLayoutModel(Keyboard.Nine, new MatrixPosition(1, 9), new LedPosition(4, 10, 31), new MatrixPosition(3, 9)) },
            { Keyboard.Zero, new KeebLayoutModel(Keyboard.Zero, new MatrixPosition(1, 10), new LedPosition(4, 11, 32), new MatrixPosition(3, 10)) },
            { Keyboard.Hyphen, new KeebLayoutModel(Keyboard.Hyphen, new MatrixPosition(1, 11), new LedPosition(4, 12, 33), new MatrixPosition(3, 11)) },
            { Keyboard.Plus, new KeebLayoutModel(Keyboard.Plus, new MatrixPosition(1, 12), new LedPosition(4, 13, 34), new MatrixPosition(3, 12)) },
            { Keyboard.BackSpace, new KeebLayoutModel(Keyboard.BackSpace, new MatrixPosition(1, 13), new LedPosition(4, 15, 35), new MatrixPosition(3, 13)) },
            { Keyboard.Insert, new KeebLayoutModel(Keyboard.Insert, new MatrixPosition(1, 14), new LedPosition(4, 17, 36), new MatrixPosition(3, 14)) },
            { Keyboard.HOME, new KeebLayoutModel(Keyboard.HOME, new MatrixPosition(1, 15), new LedPosition(4, 18, 37), new MatrixPosition(3, 15)) },
            { Keyboard.PAGEUp, new KeebLayoutModel(Keyboard.PAGEUp, new MatrixPosition(1, 16), new LedPosition(4, 19, 38), new MatrixPosition(3, 16)) },
            //Row 6
            { Keyboard.Tab, new KeebLayoutModel(Keyboard.Tab, new MatrixPosition(2, 0), new LedPosition(5, 1, 43), new MatrixPosition(4, 0)) },
            { Keyboard.Q, new KeebLayoutModel(Keyboard.Q, new MatrixPosition(2, 1), new LedPosition(5, 3, 44), new MatrixPosition(4, 1)) },
            { Keyboard.W, new KeebLayoutModel(Keyboard.W, new MatrixPosition(2, 2), new LedPosition(5, 4, 45), new MatrixPosition(4, 2)) },
            { Keyboard.E, new KeebLayoutModel(Keyboard.E, new MatrixPosition(2, 3), new LedPosition(5, 5, 46), new MatrixPosition(4, 3)) },
            { Keyboard.R, new KeebLayoutModel(Keyboard.R, new MatrixPosition(2, 4), new LedPosition(5, 6, 47), new MatrixPosition(4, 4)) },
            { Keyboard.T, new KeebLayoutModel(Keyboard.T, new MatrixPosition(2, 5), new LedPosition(5, 7, 48), new MatrixPosition(4, 5)) },
            { Keyboard.Y, new KeebLayoutModel(Keyboard.Y, new MatrixPosition(2, 6), new LedPosition(5, 8, 49), new MatrixPosition(4, 6)) },
            { Keyboard.U, new KeebLayoutModel(Keyboard.U, new MatrixPosition(2, 7), new LedPosition(5, 9, 50), new MatrixPosition(4, 7)) },
            { Keyboard.I, new KeebLayoutModel(Keyboard.I, new MatrixPosition(2, 8), new LedPosition(5, 10, 51), new MatrixPosition(4, 8)) },
            { Keyboard.O, new KeebLayoutModel(Keyboard.O, new MatrixPosition(2, 9), new LedPosition(5, 11, 52), new MatrixPosition(4, 9)) },
            { Keyboard.P, new KeebLayoutModel(Keyboard.P, new MatrixPosition(2, 10), new LedPosition(5, 12, 53), new MatrixPosition(4, 10)) },
            { Keyboard.LeftBracket, new KeebLayoutModel(Keyboard.LeftBracket, new MatrixPosition(2, 11), new LedPosition(5, 13, 54), new MatrixPosition(4, 11)) },
            { Keyboard.RightBracket, new KeebLayoutModel(Keyboard.RightBracket, new MatrixPosition(2, 12), new LedPosition(5, 14, 55), new MatrixPosition(4, 12)) },
            { Keyboard.BackSlash, new KeebLayoutModel(Keyboard.BackSlash, new MatrixPosition(2, 13), new LedPosition(5, 15, 56), new MatrixPosition(4, 13)) },
            { Keyboard.DELETE, new KeebLayoutModel(Keyboard.DELETE, new MatrixPosition(2, 14), new LedPosition(5, 17, 57), new MatrixPosition(4, 14)) },
            { Keyboard.END, new KeebLayoutModel(Keyboard.END, new MatrixPosition(2, 15), new LedPosition(5, 18, 58), new MatrixPosition(4, 15)) },
            { Keyboard.PAGEDown, new KeebLayoutModel(Keyboard.PAGEDown, new MatrixPosition(2, 16), new LedPosition(5, 19, 59), new MatrixPosition(4, 16)) },
            //Row 8
            { Keyboard.CapLock, new KeebLayoutModel(Keyboard.CapLock, new MatrixPosition(3,0), new LedPosition(6, 1 , 64), new MatrixPosition(5, 0)) },
            { Keyboard.A, new KeebLayoutModel(Keyboard.A, new MatrixPosition(3,1), new LedPosition(6, 3 , 65), new MatrixPosition(5, 1)) },
            { Keyboard.S, new KeebLayoutModel(Keyboard.S, new MatrixPosition(3,2), new LedPosition(6, 4 , 66), new MatrixPosition(5, 2)) },
            { Keyboard.D, new KeebLayoutModel(Keyboard.D, new MatrixPosition(3,3), new LedPosition(6, 5, 67), new MatrixPosition(5, 3)) },
            { Keyboard.F, new KeebLayoutModel(Keyboard.F, new MatrixPosition(3,4), new LedPosition(6, 6, 68), new MatrixPosition(5, 4)) },
            { Keyboard.G, new KeebLayoutModel(Keyboard.G, new MatrixPosition(3,5), new LedPosition(6, 7, 69), new MatrixPosition(5, 5)) },
            { Keyboard.H, new KeebLayoutModel(Keyboard.H, new MatrixPosition(3,6), new LedPosition(6, 8, 70), new MatrixPosition(5, 6)) },
            { Keyboard.J, new KeebLayoutModel(Keyboard.J, new MatrixPosition(3,7), new LedPosition(6, 9, 71), new MatrixPosition(5, 7)) },
            { Keyboard.K, new KeebLayoutModel(Keyboard.K, new MatrixPosition(3,8), new LedPosition(6, 10, 72), new MatrixPosition(5, 8)) },
            { Keyboard.L, new KeebLayoutModel(Keyboard.L, new MatrixPosition(3,9), new LedPosition(6, 11, 73), new MatrixPosition(5, 9)) },
            { Keyboard.Semicolon, new KeebLayoutModel(Keyboard.Semicolon, new MatrixPosition(3,10), new LedPosition(6, 12, 74), new MatrixPosition(5, 10)) },
            { Keyboard.SingleQuote, new KeebLayoutModel(Keyboard.SingleQuote, new MatrixPosition(3,11), new LedPosition(6, 13, 75), new MatrixPosition(5, 11)) },
            { Keyboard.Enter, new KeebLayoutModel(Keyboard.Enter, new MatrixPosition(3,13), new LedPosition(6, 15, 77), new MatrixPosition(5, 12)) },
            //Row 10
            { Keyboard.LeftShift, new KeebLayoutModel(Keyboard.LeftShift, new MatrixPosition(4, 0), new LedPosition(7, 2, 85), new MatrixPosition(6, 0)) },
            { Keyboard.Z, new KeebLayoutModel(Keyboard.Z, new MatrixPosition(4, 2), new LedPosition(7, 4, 87), new MatrixPosition(6, 1)) },
            { Keyboard.X, new KeebLayoutModel(Keyboard.X, new MatrixPosition(4, 3), new LedPosition(7, 5, 88), new MatrixPosition(6, 2)) },
            { Keyboard.C, new KeebLayoutModel(Keyboard.C, new MatrixPosition(4, 4), new LedPosition(7, 6, 89), new MatrixPosition(6, 3)) },
            { Keyboard.V, new KeebLayoutModel(Keyboard.V, new MatrixPosition(4, 5), new LedPosition(7, 7, 90), new MatrixPosition(6, 4)) },
            { Keyboard.B, new KeebLayoutModel(Keyboard.B, new MatrixPosition(4, 6), new LedPosition(7, 8, 91), new MatrixPosition(6, 5)) },
            { Keyboard.N, new KeebLayoutModel(Keyboard.N, new MatrixPosition(4, 7), new LedPosition(7, 9, 92), new MatrixPosition(6, 6)) },
            { Keyboard.M, new KeebLayoutModel(Keyboard.M, new MatrixPosition(4, 8), new LedPosition(7, 10, 93), new MatrixPosition(6, 7)) },
            { Keyboard.Comma, new KeebLayoutModel(Keyboard.Comma, new MatrixPosition(4, 9), new LedPosition(7, 11, 94), new MatrixPosition(6, 8)) },
            { Keyboard.Period, new KeebLayoutModel(Keyboard.Period, new MatrixPosition(4, 10), new LedPosition(7, 12, 95), new MatrixPosition(6, 9)) },
            { Keyboard.Slash, new KeebLayoutModel(Keyboard.Slash, new MatrixPosition(4, 11), new LedPosition(7, 13, 96), new MatrixPosition(6, 10)) },
            { Keyboard.RightShift, new KeebLayoutModel(Keyboard.RightShift, new MatrixPosition(4, 13), new LedPosition(7, 15, 98), new MatrixPosition(6, 11)) },
            { Keyboard.UP, new KeebLayoutModel(Keyboard.UP, new MatrixPosition(4, 15), new LedPosition(7, 18, 100), new MatrixPosition(6, 12)) },
            //Row 12
            { Keyboard.CTRL_L, new KeebLayoutModel(Keyboard.CTRL_L, new MatrixPosition(5, 0), new LedPosition(8, 1, 106), new MatrixPosition(7, 0)) },
            { Keyboard.WIN_L, new KeebLayoutModel(Keyboard.WIN_L, new MatrixPosition(5, 1), new LedPosition(8, 2, 107), new MatrixPosition(7, 1)) },
            { Keyboard.ALT_L, new KeebLayoutModel(Keyboard.ALT_L, new MatrixPosition(5, 2), new LedPosition(8, 3, 108), new MatrixPosition(7, 2)) },
            { Keyboard.SPACE_LL, new KeebLayoutModel(Keyboard.SPACE_LL, null, new LedPosition(8, 5, 110), null) },
            { Keyboard.SPACE_L, new KeebLayoutModel(Keyboard.SPACE_L, null, new LedPosition(8, 6, 111), null) },
            { Keyboard.SPACE, new KeebLayoutModel(Keyboard.SPACE, new MatrixPosition(5, 6), new LedPosition(8, 7, 112), new MatrixPosition(7, 3)) },
            { Keyboard.SPACE_R, new KeebLayoutModel(Keyboard.SPACE_R, null, new LedPosition(8, 8, 113), null) },
            { Keyboard.SPACE_RR, new KeebLayoutModel(Keyboard.SPACE_RR, null, new LedPosition(8, 9, 114), null) },
            { Keyboard.ALT_R, new KeebLayoutModel(Keyboard.ALT_R, new MatrixPosition(5, 10), new LedPosition(8, 12, 116), new MatrixPosition(7, 4)) },
            { Keyboard.FN, new KeebLayoutModel(Keyboard.FN, new MatrixPosition(5, 11), new LedPosition(8, 13, 117), new MatrixPosition(7, 5)) },
            { Keyboard.Menu, new KeebLayoutModel(Keyboard.Menu, new MatrixPosition(5, 12), new LedPosition(8, 14, 118), new MatrixPosition(7, 6)) },
            { Keyboard.CTRL_R, new KeebLayoutModel(Keyboard.CTRL_R, new MatrixPosition(5, 13), new LedPosition(8, 15, 119), new MatrixPosition(7, 7)) },
            { Keyboard.LEFT, new KeebLayoutModel(Keyboard.LEFT, new MatrixPosition(5, 14), new LedPosition(8, 17, 120), new MatrixPosition(7, 8)) },
            { Keyboard.DOWN, new KeebLayoutModel(Keyboard.DOWN, new MatrixPosition(5, 15), new LedPosition(8, 18, 121), new MatrixPosition(7, 9)) },
            { Keyboard.RIGHT, new KeebLayoutModel(Keyboard.RIGHT, new MatrixPosition(5, 16), new LedPosition(8, 19, 122), new MatrixPosition(7, 10)) },
        };

        public static List<Keyboard> ANSIButtonPusherKeys =>
        [
            //Keyboard.ESC, Keyboard.F1, Keyboard.F2, Keyboard.F3, Keyboard.F4, Keyboard.F5, Keyboard.F6, Keyboard.F7, Keyboard.F8, Keyboard.F9, Keyboard.F10, Keyboard.F11, Keyboard.F12,
            Keyboard.Tilde, Keyboard.One, Keyboard.Two, Keyboard.Three, Keyboard.Four, Keyboard.Five, Keyboard.Six, Keyboard.Seven, Keyboard.Eight, Keyboard.Nine, Keyboard.Zero, Keyboard.Hyphen, Keyboard.Plus, Keyboard.BackSpace,
            Keyboard.Tab, Keyboard.Q, Keyboard.W, Keyboard.E, Keyboard.R, Keyboard.T, Keyboard.Y, Keyboard.U, Keyboard.I, Keyboard.O, Keyboard.P, Keyboard.LeftBracket, Keyboard.RightBracket, Keyboard.BackSlash,
            Keyboard.CapLock, Keyboard.A, Keyboard.S, Keyboard.D, Keyboard.F, Keyboard.G, Keyboard.H, Keyboard.J, Keyboard.K, Keyboard.L, Keyboard.Semicolon, Keyboard.SingleQuote, Keyboard.Enter,
            Keyboard.LeftShift, Keyboard.Z, Keyboard.X, Keyboard.C, Keyboard.V, Keyboard.B, Keyboard.N, Keyboard.M, Keyboard.Comma, Keyboard.Period, Keyboard.Slash, Keyboard.RightShift,
            //Keyboard.CTRL_L, Keyboard.WIN_L, Keyboard.ALT_L, Keyboard.ALT_R, Keyboard.FN, Keyboard.MOUSE, Keyboard.CTRL_R,
            Keyboard.SPACE,
            //Keyboard.PrnSrc, Keyboard.ScrLk, Keyboard.Pause, Keyboard.Insert, Keyboard.NumLock, Keyboard.NumBackSlash, Keyboard.NUM_Multiple, Keyboard.NUM_Hypen,
            //Keyboard.NUM_1, Keyboard.NUM_2, Keyboard.NUM_3, Keyboard.NUM_4, Keyboard.NUM_5, Keyboard.NUM_6, Keyboard.NUM_7, Keyboard.NUM_8, Keyboard.NUM_9, Keyboard.NUM_0, Keyboard.NUM_Plus, Keyboard.NUM_DEL, Keyboard.NUM_Enter,
            //Keyboard.DELETE, Keyboard.HOME, Keyboard.PAGEUp, Keyboard.PAGEDown, Keyboard.UP, Keyboard.DOWN, Keyboard.LEFT, Keyboard.RIGHT, Keyboard.DEL, Keyboard.END,
        ];
        #endregion

        #region Keeb ISO
        public static readonly List<KeebLayoutModel> ISOLayout =
        [
            //Row 1
            new KeebLayoutModel(Keyboard.TopLED1, null, new LedPosition(0, 1, 136), null),
            new KeebLayoutModel(Keyboard.TopLED2, null, new LedPosition(0, 2 , 135), null),
            new KeebLayoutModel(Keyboard.TopLED3, null, new LedPosition(0, 3 , 134), null),
            new KeebLayoutModel(Keyboard.TopLED4, null, new LedPosition(0, 4 , 133), null),
            new KeebLayoutModel(Keyboard.TopLED5, null, new LedPosition(0, 5 , 132), null),
            new KeebLayoutModel(Keyboard.TopLED6, null, new LedPosition(0, 6 , 131), null),
            new KeebLayoutModel(Keyboard.TopLED7, null, new LedPosition(0, 7 , 130), null),
            new KeebLayoutModel(Keyboard.TopLED8, null, new LedPosition(0, 8 , 129), null),
            new KeebLayoutModel(Keyboard.TopLED9, null, new LedPosition(0, 9 , 128), null),
            new KeebLayoutModel(Keyboard.TopLED10, null, new LedPosition(0, 10, 127), null),
            new KeebLayoutModel(Keyboard.TopLED11, null, new LedPosition(0, 11, 176), null),
            new KeebLayoutModel(Keyboard.TopLED12, null, new LedPosition(0, 12, 175), null),
            new KeebLayoutModel(Keyboard.TopLED13, null, new LedPosition(0, 13, 174), null),
            new KeebLayoutModel(Keyboard.TopLED14, null, new LedPosition(0, 14, 173), null),
            new KeebLayoutModel(Keyboard.TopLED15, null, new LedPosition(0, 15, 172), null),
            new KeebLayoutModel(Keyboard.TopLED16, null, new LedPosition(0, 16, 171), null),
            new KeebLayoutModel(Keyboard.TopLED17, null, new LedPosition(0, 17, 170), null),
            new KeebLayoutModel(Keyboard.TopLED18, null, new LedPosition(0, 18, 169), null),
            new KeebLayoutModel(Keyboard.TopLED19, null, new LedPosition(0, 19, 168), null),
            //Row 2
            new KeebLayoutModel(Keyboard.ScrollWheel, null, new LedPosition(1, 3 , 177), null),
            //Row 3
            new KeebLayoutModel(Keyboard.MediaLED1, new MatrixPosition(3, 14) , new LedPosition(2, 1, 78), new MatrixPosition(1, 0)),
            new KeebLayoutModel(Keyboard.MediaLED2, new MatrixPosition(3, 15), new LedPosition(2, 2, 79), new MatrixPosition(1, 1)),
            new KeebLayoutModel(Keyboard.MediaLED3,  new MatrixPosition(3, 16), new LedPosition(2, 3, 80), new MatrixPosition(1, 2)),
            new KeebLayoutModel(Keyboard.MediaLED4,  new MatrixPosition(4, 14), new LedPosition(2, 4, 99), new MatrixPosition(1, 3)),
            new KeebLayoutModel(Keyboard.MediaLED5,  new MatrixPosition(4, 16), new LedPosition(2, 5, 101), new MatrixPosition(1, 4)),
            //Row 4
            new KeebLayoutModel(Keyboard.LeftLED1,     null, new LedPosition(3, 0 , 137), null),
            new KeebLayoutModel(Keyboard.ESC,          new MatrixPosition(0,0), new LedPosition(3, 1 , 1),  new MatrixPosition(2, 0)),
            new KeebLayoutModel(Keyboard.F1,           new MatrixPosition(0,2), new LedPosition(3, 3 , 3),  new MatrixPosition(2, 1)),
            new KeebLayoutModel(Keyboard.F2,           new MatrixPosition(0,3), new LedPosition(3, 4 , 4),  new MatrixPosition(2, 2)),
            new KeebLayoutModel(Keyboard.F3,           new MatrixPosition(0,4), new LedPosition(3, 5 , 5),  new MatrixPosition(2, 3)),
            new KeebLayoutModel(Keyboard.F4,           new MatrixPosition(0,5), new LedPosition(3, 6 , 6),  new MatrixPosition(2, 4)),
            new KeebLayoutModel(Keyboard.F5,           new MatrixPosition(0,6), new LedPosition(3, 8, 7),   new MatrixPosition(2, 5)),
            new KeebLayoutModel(Keyboard.F6,           new MatrixPosition(0,7), new LedPosition(3, 9, 8),   new MatrixPosition(2, 6)),
            new KeebLayoutModel(Keyboard.F7,           new MatrixPosition(0,8), new LedPosition(3, 10, 9),  new MatrixPosition(2, 7)),
            new KeebLayoutModel(Keyboard.F8,           new MatrixPosition(0,9), new LedPosition(3, 11, 10), new MatrixPosition(2, 8)),
            new KeebLayoutModel(Keyboard.F9,           new MatrixPosition(0,10), new LedPosition(3, 13, 11), new MatrixPosition(2, 9)),
            new KeebLayoutModel(Keyboard.F10,          new MatrixPosition(0,11), new LedPosition(3, 14, 12), new MatrixPosition(2, 10)),
            new KeebLayoutModel(Keyboard.F11,          new MatrixPosition(0,12), new LedPosition(3, 15, 13), new MatrixPosition(2, 11)),
            new KeebLayoutModel(Keyboard.F12,          new MatrixPosition(0,13), new LedPosition(3, 16, 14), new MatrixPosition(2, 12)),
            new KeebLayoutModel(Keyboard.Pause,        new MatrixPosition(0,14), new LedPosition(3, 17, 15), new MatrixPosition(2, 13)),
            new KeebLayoutModel(Keyboard.ScrLk,        new MatrixPosition(0,15), new LedPosition(3, 18, 16), new MatrixPosition(2, 14)),
            new KeebLayoutModel(Keyboard.PrnSrc,       new MatrixPosition(0,16), new LedPosition(3, 19, 17), new MatrixPosition(2, 15)),
            new KeebLayoutModel(Keyboard.RightLED1,    null, new LedPosition(3, 20, 167), null),
            //Row 5
            new KeebLayoutModel(Keyboard.LeftLED2,       null, new LedPosition(4, 0 , 138), null),
            new KeebLayoutModel(Keyboard.Tilde,          new MatrixPosition(1,0), new LedPosition(4, 1 , 22), new MatrixPosition(3, 0)),
            new KeebLayoutModel(Keyboard.One,            new MatrixPosition(1,1), new LedPosition(4, 2 , 23), new MatrixPosition(3, 1)),
            new KeebLayoutModel(Keyboard.Two,            new MatrixPosition(1,2), new LedPosition(4, 3 , 24), new MatrixPosition(3, 2)),
            new KeebLayoutModel(Keyboard.Three,          new MatrixPosition(1,3), new LedPosition(4, 4 , 25), new MatrixPosition(3, 3)),
            new KeebLayoutModel(Keyboard.Four,           new MatrixPosition(1,4), new LedPosition(4, 5, 26), new MatrixPosition(3, 4)),
            new KeebLayoutModel(Keyboard.Five,           new MatrixPosition(1,5), new LedPosition(4, 6, 27), new MatrixPosition(3, 5)),
            new KeebLayoutModel(Keyboard.Six,            new MatrixPosition(1,6), new LedPosition(4, 7, 28), new MatrixPosition(3, 6)),
            new KeebLayoutModel(Keyboard.Seven,          new MatrixPosition(1,7), new LedPosition(4, 8, 29), new MatrixPosition(3, 7)),
            new KeebLayoutModel(Keyboard.Eight,          new MatrixPosition(1,8), new LedPosition(4, 9, 30), new MatrixPosition(3, 8)),
            new KeebLayoutModel(Keyboard.Nine,           new MatrixPosition(1,9), new LedPosition(4, 10, 31), new MatrixPosition(3, 9)),
            new KeebLayoutModel(Keyboard.Zero,           new MatrixPosition(1,10), new LedPosition(4, 11, 32), new MatrixPosition(3, 10)),
            new KeebLayoutModel(Keyboard.Hyphen,         new MatrixPosition(1,11), new LedPosition(4, 12, 33), new MatrixPosition(3, 11)),
            new KeebLayoutModel(Keyboard.Plus,           new MatrixPosition(1,12), new LedPosition(4, 13, 34), new MatrixPosition(3, 12)),
            new KeebLayoutModel(Keyboard.BackSpace,      new MatrixPosition(1,13), new LedPosition(4, 15, 35), new MatrixPosition(3, 13)),
            new KeebLayoutModel(Keyboard.Insert,         new MatrixPosition(1,14), new LedPosition(4, 17, 36), new MatrixPosition(3, 14)),
            new KeebLayoutModel(Keyboard.HOME,           new MatrixPosition(1,15), new LedPosition(4, 18, 37), new MatrixPosition(3, 15)),
            new KeebLayoutModel(Keyboard.PAGEUp,         new MatrixPosition(1,16), new LedPosition(4, 19, 38), new MatrixPosition(3, 16)),
            new KeebLayoutModel(Keyboard.RightLED2,      null, new LedPosition(4, 20, 166), null),
            //Row 6
            new KeebLayoutModel(Keyboard.LeftLED3,     null, new LedPosition(5, 0 , 139), null),
            new KeebLayoutModel(Keyboard.Tab,          new MatrixPosition(2,0), new LedPosition(5, 1 , 43), new MatrixPosition(4, 0)),
            new KeebLayoutModel(Keyboard.Q,            new MatrixPosition(2,1), new LedPosition(5, 3 , 44), new MatrixPosition(4, 1)),
            new KeebLayoutModel(Keyboard.W,            new MatrixPosition(2,2), new LedPosition(5, 4 , 45), new MatrixPosition(4, 2)),
            new KeebLayoutModel(Keyboard.E,            new MatrixPosition(2,3), new LedPosition(5, 5 , 46), new MatrixPosition(4, 3)),
            new KeebLayoutModel(Keyboard.R,            new MatrixPosition(2,4), new LedPosition(5, 6, 47), new MatrixPosition(4, 4)),
            new KeebLayoutModel(Keyboard.T,            new MatrixPosition(2,5), new LedPosition(5, 7, 48), new MatrixPosition(4, 5)),
            new KeebLayoutModel(Keyboard.Y,            new MatrixPosition(2,6), new LedPosition(5, 8, 49), new MatrixPosition(4, 6)),
            new KeebLayoutModel(Keyboard.U,            new MatrixPosition(2,7), new LedPosition(5, 9, 50), new MatrixPosition(4, 7)),
            new KeebLayoutModel(Keyboard.I,            new MatrixPosition(2,8), new LedPosition(5, 10, 51), new MatrixPosition(4, 8)),
            new KeebLayoutModel(Keyboard.O,            new MatrixPosition(2,9), new LedPosition(5, 11, 52), new MatrixPosition(4, 9)),
            new KeebLayoutModel(Keyboard.P,            new MatrixPosition(2,10), new LedPosition(5, 12, 53), new MatrixPosition(4, 10)),
            new KeebLayoutModel(Keyboard.LeftBracket,  new MatrixPosition(2,11), new LedPosition(5, 13, 54), new MatrixPosition(4, 11)),
            new KeebLayoutModel(Keyboard.RightBracket, new MatrixPosition(2,12), new LedPosition(5, 14, 55), new MatrixPosition(4, 12)),
            new KeebLayoutModel(Keyboard.DELETE,       new MatrixPosition(2,14), new LedPosition(5, 17, 57), new MatrixPosition(4, 14)),
            new KeebLayoutModel(Keyboard.END,          new MatrixPosition(2,15), new LedPosition(5, 18, 58), new MatrixPosition(4, 15)),
            new KeebLayoutModel(Keyboard.PAGEDown,     new MatrixPosition(2,16), new LedPosition(5, 19, 59), new MatrixPosition(4, 16)),
            new KeebLayoutModel(Keyboard.RightLED3,    null, new LedPosition(5, 20, 165), null),
            //Row 8
            new KeebLayoutModel(Keyboard.LeftLED4,     null, new LedPosition(6, 0 , 140), null),
            new KeebLayoutModel(Keyboard.CapLock,      new MatrixPosition(3,0), new LedPosition(6, 1 , 64), new MatrixPosition(5, 0)),
            new KeebLayoutModel(Keyboard.A,            new MatrixPosition(3,1), new LedPosition(6, 3 , 65), new MatrixPosition(5, 1)),
            new KeebLayoutModel(Keyboard.S,            new MatrixPosition(3,2), new LedPosition(6, 4 , 66), new MatrixPosition(5, 2)),
            new KeebLayoutModel(Keyboard.D,            new MatrixPosition(3,3), new LedPosition(6, 5, 67), new MatrixPosition(5, 3)),
            new KeebLayoutModel(Keyboard.F,            new MatrixPosition(3,4), new LedPosition(6, 6, 68), new MatrixPosition(5, 4)),
            new KeebLayoutModel(Keyboard.G,            new MatrixPosition(3,5), new LedPosition(6, 7, 69), new MatrixPosition(5, 5)),
            new KeebLayoutModel(Keyboard.H,            new MatrixPosition(3,6), new LedPosition(6, 8, 70), new MatrixPosition(5, 6)),
            new KeebLayoutModel(Keyboard.J,            new MatrixPosition(3,7), new LedPosition(6, 9, 71), new MatrixPosition(5, 7)),
            new KeebLayoutModel(Keyboard.K,            new MatrixPosition(3,8), new LedPosition(6, 10, 72), new MatrixPosition(5, 8)),
            new KeebLayoutModel(Keyboard.L,            new MatrixPosition(3,9), new LedPosition(6, 11, 73), new MatrixPosition(5, 9)),
            new KeebLayoutModel(Keyboard.Semicolon,    new MatrixPosition(3,10), new LedPosition(6, 12, 74), new MatrixPosition(5, 10)),
            new KeebLayoutModel(Keyboard.SingleQuote,  new MatrixPosition(3,11), new LedPosition(6, 13, 75), new MatrixPosition(5, 11)),
            new KeebLayoutModel(Keyboard.Europe1,      new MatrixPosition(3,12), new LedPosition(6, 14, 76), new MatrixPosition(5, 12)),
            new KeebLayoutModel(Keyboard.Enter,        new MatrixPosition(3,13), new LedPosition(5, 15, 77), new MatrixPosition(4, 13)),
            new KeebLayoutModel(Keyboard.RightLED4,    null, new LedPosition(6, 20, 164), null),
            //Row 10
            new KeebLayoutModel(Keyboard.LeftLED5,     null, new LedPosition(7, 0 , 141), null),
            new KeebLayoutModel(Keyboard.LeftShift,    new MatrixPosition(4,0), new LedPosition(7, 2 , 85), new MatrixPosition(6, 0)),
            new KeebLayoutModel(Keyboard.Europe2,      new MatrixPosition(4,1), new LedPosition(7, 1 , 86), new MatrixPosition(6, 1)),
            new KeebLayoutModel(Keyboard.Z,            new MatrixPosition(4,2), new LedPosition(7, 4 , 87), new MatrixPosition(6, 2)),
            new KeebLayoutModel(Keyboard.X,            new MatrixPosition(4,3), new LedPosition(7, 5 , 88), new MatrixPosition(6, 3)),
            new KeebLayoutModel(Keyboard.C,            new MatrixPosition(4,4), new LedPosition(7, 6, 89), new MatrixPosition(6, 4)),
            new KeebLayoutModel(Keyboard.V,            new MatrixPosition(4,5), new LedPosition(7, 7, 90), new MatrixPosition(6, 5)),
            new KeebLayoutModel(Keyboard.B,            new MatrixPosition(4,6), new LedPosition(7, 8, 91), new MatrixPosition(6, 6)),
            new KeebLayoutModel(Keyboard.N,            new MatrixPosition(4,7), new LedPosition(7, 9, 92), new MatrixPosition(6, 7)),
            new KeebLayoutModel(Keyboard.M,            new MatrixPosition(4,8), new LedPosition(7, 10, 93), new MatrixPosition(6, 8)),
            new KeebLayoutModel(Keyboard.Comma,        new MatrixPosition(4,9), new LedPosition(7, 11, 94), new MatrixPosition(6, 9)),
            new KeebLayoutModel(Keyboard.Period,       new MatrixPosition(4,10), new LedPosition(7, 12, 95), new MatrixPosition(6, 10)),
            new KeebLayoutModel(Keyboard.Slash,        new MatrixPosition(4,11), new LedPosition(7, 13, 96), new MatrixPosition(6, 11)),
            new KeebLayoutModel(Keyboard.RightShift,   new MatrixPosition(4,13), new LedPosition(7, 15, 98), new MatrixPosition(6, 12)),
            new KeebLayoutModel(Keyboard.UP,           new MatrixPosition(4,15), new LedPosition(7, 18, 100), new MatrixPosition(6, 13)),
            new KeebLayoutModel(Keyboard.RightLED5,    null, new LedPosition(7, 20, 163), null),
            //Row 12
            new KeebLayoutModel(Keyboard.LeftLED6,     null, new LedPosition(8, 0 , 142), null),
            new KeebLayoutModel(Keyboard.CTRL_L,       new MatrixPosition(5,0), new LedPosition(8, 1, 106), new MatrixPosition(7, 0)),
            new KeebLayoutModel(Keyboard.WIN_L,        new MatrixPosition(5,1), new LedPosition(8, 2, 107), new MatrixPosition(7, 1)),
            new KeebLayoutModel(Keyboard.ALT_L,        new MatrixPosition(5,2), new LedPosition(8, 3, 108), new MatrixPosition(7, 2)),
            new KeebLayoutModel(Keyboard.SPACE_LL,     null, new LedPosition(8, 5, 110), null),
            new KeebLayoutModel(Keyboard.SPACE_L,      null, new LedPosition(8, 6, 111), null),
            new KeebLayoutModel(Keyboard.SPACE,        new MatrixPosition(5,6), new LedPosition(8, 7, 112), new MatrixPosition(7, 3)),
            new KeebLayoutModel(Keyboard.SPACE_R,      null, new LedPosition(8, 8, 113), null),
            new KeebLayoutModel(Keyboard.SPACE_RR,     null, new LedPosition(8, 9, 114), null),
            new KeebLayoutModel(Keyboard.ALT_R,        new MatrixPosition(5,10), new LedPosition(8, 12, 116), new MatrixPosition(7, 4)),
            new KeebLayoutModel(Keyboard.FN,           new MatrixPosition(5,11), new LedPosition(8, 13, 117), new MatrixPosition(7, 5)),
            new KeebLayoutModel(Keyboard.Menu,         new MatrixPosition(5,12), new LedPosition(8, 14, 118), new MatrixPosition(7, 6)),
            new KeebLayoutModel(Keyboard.CTRL_R,       new MatrixPosition(5,13), new LedPosition(8, 15, 119), new MatrixPosition(7, 7)),
            new KeebLayoutModel(Keyboard.LEFT,         new MatrixPosition(5,14), new LedPosition(8, 17, 120), new MatrixPosition(7, 8)),
            new KeebLayoutModel(Keyboard.DOWN,         new MatrixPosition(5,15), new LedPosition(8, 18, 121), new MatrixPosition(7, 9)),
            new KeebLayoutModel(Keyboard.RIGHT,        new MatrixPosition(5,16), new LedPosition(8, 19, 122), new MatrixPosition(7, 10)),
            new KeebLayoutModel(Keyboard.RightLED6,    null, new LedPosition(8, 20, 162), null),
            //Row 14
            new KeebLayoutModel(Keyboard.BottomLED1,   null, new LedPosition(9, 1, 143), null),
            new KeebLayoutModel(Keyboard.BottomLED2,   null, new LedPosition(9, 2, 144), null),
            new KeebLayoutModel(Keyboard.BottomLED3,   null, new LedPosition(9, 3, 145), null),
            new KeebLayoutModel(Keyboard.BottomLED4,   null, new LedPosition(9, 4, 146), null),
            new KeebLayoutModel(Keyboard.BottomLED5,   null, new LedPosition(9, 5, 147), null),
            new KeebLayoutModel(Keyboard.BottomLED6,   null, new LedPosition(9, 6, 148), null),
            new KeebLayoutModel(Keyboard.BottomLED7,   null, new LedPosition(9, 7, 149), null),
            new KeebLayoutModel(Keyboard.BottomLED8,   null, new LedPosition(9, 8, 150), null),
            new KeebLayoutModel(Keyboard.BottomLED9,   null, new LedPosition(9, 9, 151), null),
            new KeebLayoutModel(Keyboard.BottomLED10,  null, new LedPosition(9, 10, 152), null),
            new KeebLayoutModel(Keyboard.BottomLED11,  null, new LedPosition(9, 11, 153), null),
            new KeebLayoutModel(Keyboard.BottomLED12,  null, new LedPosition(9, 12, 154), null),
            new KeebLayoutModel(Keyboard.BottomLED13,  null, new LedPosition(9, 13, 155), null),
            new KeebLayoutModel(Keyboard.BottomLED14,  null, new LedPosition(9, 14, 156), null),
            new KeebLayoutModel(Keyboard.BottomLED15,  null, new LedPosition(9, 15, 157), null),
            new KeebLayoutModel(Keyboard.BottomLED16,  null, new LedPosition(9, 16, 158), null),
            new KeebLayoutModel(Keyboard.BottomLED17,  null, new LedPosition(9, 17, 159), null),
            new KeebLayoutModel(Keyboard.BottomLED18,  null, new LedPosition(9, 18, 160), null),
            new KeebLayoutModel(Keyboard.BottomLED19,  null, new LedPosition(9, 19, 161), null),
        ];

        public static Dictionary<Keyboard, KeebLayoutModel> ISO_BUTTON_KEY_LAYOUT_DICTIONAY => new()
        {
            //Row 1
            { Keyboard.TopLED1, new KeebLayoutModel(Keyboard.TopLED1, null, new LedPosition(0, 1, 136), null)},
            { Keyboard.TopLED2, new KeebLayoutModel(Keyboard.TopLED2, null, new LedPosition(0, 2 , 135), null)},
            { Keyboard.TopLED3, new KeebLayoutModel(Keyboard.TopLED3, null, new LedPosition(0, 3 , 134), null)},
            { Keyboard.TopLED4, new KeebLayoutModel(Keyboard.TopLED4, null, new LedPosition(0, 4 , 133), null)},
            { Keyboard.TopLED5, new KeebLayoutModel(Keyboard.TopLED5, null, new LedPosition(0, 5 , 132), null)},
            { Keyboard.TopLED6,  new KeebLayoutModel(Keyboard.TopLED6, null, new LedPosition(0, 6 , 131), null)},
            { Keyboard.TopLED7,  new KeebLayoutModel(Keyboard.TopLED7, null, new LedPosition(0, 7 , 130), null)},
            { Keyboard.TopLED8,  new KeebLayoutModel(Keyboard.TopLED8, null, new LedPosition(0, 8 , 129), null)},
            { Keyboard.TopLED9, new KeebLayoutModel(Keyboard.TopLED9, null, new LedPosition(0, 9 , 128), null)},
            { Keyboard.TopLED10, new KeebLayoutModel(Keyboard.TopLED10, null, new LedPosition(0, 10, 127), null)},
            { Keyboard.TopLED11, new KeebLayoutModel(Keyboard.TopLED11, null, new LedPosition(0, 11, 176), null)},
            { Keyboard.TopLED12, new KeebLayoutModel(Keyboard.TopLED12, null, new LedPosition(0, 12, 175), null)},
            { Keyboard.TopLED13, new KeebLayoutModel(Keyboard.TopLED13, null, new LedPosition(0, 13, 174), null)},
            { Keyboard.TopLED14, new KeebLayoutModel(Keyboard.TopLED14, null, new LedPosition(0, 14, 173), null)},
            { Keyboard.TopLED15, new KeebLayoutModel(Keyboard.TopLED15, null, new LedPosition(0, 15, 172), null)},
            { Keyboard.TopLED16, new KeebLayoutModel(Keyboard.TopLED16, null, new LedPosition(0, 16, 171), null)},
            { Keyboard.TopLED17,  new KeebLayoutModel(Keyboard.TopLED17, null, new LedPosition(0, 17, 170), null)},
            { Keyboard.TopLED18, new KeebLayoutModel(Keyboard.TopLED18, null, new LedPosition(0, 18, 169), null)},
            { Keyboard.TopLED19, new KeebLayoutModel(Keyboard.TopLED19, null, new LedPosition(0, 19, 168), null)},
            //Row 2
            { Keyboard.ScrollWheel, new KeebLayoutModel(Keyboard.ScrollWheel, null, new LedPosition(1, 2 , 177), null)},
            //Row 3
            { Keyboard.MediaLED1, new KeebLayoutModel(Keyboard.MediaLED1, new MatrixPosition(3, 14) , new LedPosition(2, 1, 78), new MatrixPosition(1, 0))},
            { Keyboard.MediaLED2, new KeebLayoutModel(Keyboard.MediaLED2, new MatrixPosition(3, 15), new LedPosition(2, 2, 79), new MatrixPosition(1, 1))},
            { Keyboard.MediaLED3, new KeebLayoutModel(Keyboard.MediaLED3,  new MatrixPosition(3, 16), new LedPosition(2, 3, 80), new MatrixPosition(1, 2))},
            { Keyboard.MediaLED4, new KeebLayoutModel(Keyboard.MediaLED4,  new MatrixPosition(4, 14), new LedPosition(2, 4, 99), new MatrixPosition(1, 3))},
            { Keyboard.MediaLED5, new KeebLayoutModel(Keyboard.MediaLED5,  new MatrixPosition(4, 16), new LedPosition(2, 5, 101), new MatrixPosition(1, 4))},
            //Row 4
            { Keyboard.ESC, new KeebLayoutModel(Keyboard.ESC, new MatrixPosition(0, 0), new LedPosition(3, 1, 1), new MatrixPosition(2, 0)) },
            { Keyboard.F1, new KeebLayoutModel(Keyboard.F1, new MatrixPosition(0, 2), new LedPosition(3, 3, 3), new MatrixPosition(2, 1)) },
            { Keyboard.F2, new KeebLayoutModel(Keyboard.F2, new MatrixPosition(0, 3), new LedPosition(3, 4, 4), new MatrixPosition(2, 2)) },
            { Keyboard.F3, new KeebLayoutModel(Keyboard.F3, new MatrixPosition(0, 4), new LedPosition(3, 5, 5), new MatrixPosition(2, 3)) },
            { Keyboard.F4, new KeebLayoutModel(Keyboard.F4, new MatrixPosition(0, 5), new LedPosition(3, 6, 6), new MatrixPosition(2, 4)) },
            { Keyboard.F5, new KeebLayoutModel(Keyboard.F5, new MatrixPosition(0, 6), new LedPosition(3, 8, 7), new MatrixPosition(2, 5)) },
            { Keyboard.F6, new KeebLayoutModel(Keyboard.F6, new MatrixPosition(0, 7), new LedPosition(3, 9, 8), new MatrixPosition(2, 6)) },
            { Keyboard.F7, new KeebLayoutModel(Keyboard.F7, new MatrixPosition(0, 8), new LedPosition(3, 10, 9), new MatrixPosition(2, 7)) },
            { Keyboard.F8, new KeebLayoutModel(Keyboard.F8, new MatrixPosition(0, 9), new LedPosition(3, 11, 10), new MatrixPosition(2, 8)) },
            { Keyboard.F9, new KeebLayoutModel(Keyboard.F9, new MatrixPosition(0, 10), new LedPosition(3, 13, 11), new MatrixPosition(2, 9)) },
            { Keyboard.F10, new KeebLayoutModel(Keyboard.F10, new MatrixPosition(0, 11), new LedPosition(3, 14, 12), new MatrixPosition(2, 10)) },
            { Keyboard.F11, new KeebLayoutModel(Keyboard.F11, new MatrixPosition(0, 12), new LedPosition(3, 15, 13), new MatrixPosition(2, 11)) },
            { Keyboard.F12, new KeebLayoutModel(Keyboard.F12, new MatrixPosition(0, 13), new LedPosition(3, 16, 14), new MatrixPosition(2, 12)) },
            { Keyboard.Pause, new KeebLayoutModel(Keyboard.Pause, new MatrixPosition(0, 14), new LedPosition(3, 17, 15), new MatrixPosition(2, 13)) },
            { Keyboard.ScrLk, new KeebLayoutModel(Keyboard.ScrLk, new MatrixPosition(0, 15), new LedPosition(3, 18, 16), new MatrixPosition(2, 14)) },
            { Keyboard.PrnSrc, new KeebLayoutModel(Keyboard.PrnSrc, new MatrixPosition(0, 16), new LedPosition(3, 19, 17), new MatrixPosition(2, 15)) },
            //Row 5
            { Keyboard.Tilde, new KeebLayoutModel(Keyboard.Tilde, new MatrixPosition(1, 0), new LedPosition(4, 1, 22), new MatrixPosition(3, 0)) },
            { Keyboard.One, new KeebLayoutModel(Keyboard.One, new MatrixPosition(1, 1), new LedPosition(4, 2, 23), new MatrixPosition(3, 1)) },
            { Keyboard.Two, new KeebLayoutModel(Keyboard.Two, new MatrixPosition(1, 2), new LedPosition(4, 3, 24), new MatrixPosition(3, 2)) },
            { Keyboard.Three, new KeebLayoutModel(Keyboard.Three, new MatrixPosition(1, 3), new LedPosition(4, 4, 25), new MatrixPosition(3, 3)) },
            { Keyboard.Four, new KeebLayoutModel(Keyboard.Four, new MatrixPosition(1, 4), new LedPosition(4, 5, 26), new MatrixPosition(3, 4)) },
            { Keyboard.Five, new KeebLayoutModel(Keyboard.Five, new MatrixPosition(1, 5), new LedPosition(4, 6, 27), new MatrixPosition(3, 5)) },
            { Keyboard.Six, new KeebLayoutModel(Keyboard.Six, new MatrixPosition(1, 6), new LedPosition(4, 7, 28), new MatrixPosition(3, 6)) },
            { Keyboard.Seven, new KeebLayoutModel(Keyboard.Seven, new MatrixPosition(1, 7), new LedPosition(4, 8, 29), new MatrixPosition(3, 7)) },
            { Keyboard.Eight, new KeebLayoutModel(Keyboard.Eight, new MatrixPosition(1, 8), new LedPosition(4, 9, 30), new MatrixPosition(3, 8)) },
            { Keyboard.Nine, new KeebLayoutModel(Keyboard.Nine, new MatrixPosition(1, 9), new LedPosition(4, 10, 31), new MatrixPosition(3, 9)) },
            { Keyboard.Zero, new KeebLayoutModel(Keyboard.Zero, new MatrixPosition(1, 10), new LedPosition(4, 11, 32), new MatrixPosition(3, 10)) },
            { Keyboard.Hyphen, new KeebLayoutModel(Keyboard.Hyphen, new MatrixPosition(1, 11), new LedPosition(4, 12, 33), new MatrixPosition(3, 11)) },
            { Keyboard.Plus, new KeebLayoutModel(Keyboard.Plus, new MatrixPosition(1, 12), new LedPosition(4, 13, 34), new MatrixPosition(3, 12)) },
            { Keyboard.BackSpace, new KeebLayoutModel(Keyboard.BackSpace, new MatrixPosition(1, 13), new LedPosition(4, 15, 35), new MatrixPosition(3, 13)) },
            { Keyboard.Insert, new KeebLayoutModel(Keyboard.Insert, new MatrixPosition(1, 14), new LedPosition(4, 17, 36), new MatrixPosition(3, 14)) },
            { Keyboard.HOME, new KeebLayoutModel(Keyboard.HOME, new MatrixPosition(1, 15), new LedPosition(4, 18, 37), new MatrixPosition(3, 15)) },
            { Keyboard.PAGEUp, new KeebLayoutModel(Keyboard.PAGEUp, new MatrixPosition(1, 16), new LedPosition(4, 19, 38), new MatrixPosition(3, 16)) },
            //Row 6
            { Keyboard.Tab, new KeebLayoutModel(Keyboard.Tab, new MatrixPosition(2, 0), new LedPosition(5, 1, 43), new MatrixPosition(4, 0)) },
            { Keyboard.Q, new KeebLayoutModel(Keyboard.Q, new MatrixPosition(2, 1), new LedPosition(5, 3, 44), new MatrixPosition(4, 1)) },
            { Keyboard.W, new KeebLayoutModel(Keyboard.W, new MatrixPosition(2, 2), new LedPosition(5, 4, 45), new MatrixPosition(4, 2)) },
            { Keyboard.E, new KeebLayoutModel(Keyboard.E, new MatrixPosition(2, 3), new LedPosition(5, 5, 46), new MatrixPosition(4, 3)) },
            { Keyboard.R, new KeebLayoutModel(Keyboard.R, new MatrixPosition(2, 4), new LedPosition(5, 6, 47), new MatrixPosition(4, 4)) },
            { Keyboard.T, new KeebLayoutModel(Keyboard.T, new MatrixPosition(2, 5), new LedPosition(5, 7, 48), new MatrixPosition(4, 5)) },
            { Keyboard.Y, new KeebLayoutModel(Keyboard.Y, new MatrixPosition(2, 6), new LedPosition(5, 8, 49), new MatrixPosition(4, 6)) },
            { Keyboard.U, new KeebLayoutModel(Keyboard.U, new MatrixPosition(2, 7), new LedPosition(5, 9, 50), new MatrixPosition(4, 7)) },
            { Keyboard.I, new KeebLayoutModel(Keyboard.I, new MatrixPosition(2, 8), new LedPosition(5, 10, 51), new MatrixPosition(4, 8)) },
            { Keyboard.O, new KeebLayoutModel(Keyboard.O, new MatrixPosition(2, 9), new LedPosition(5, 11, 52), new MatrixPosition(4, 9)) },
            { Keyboard.P, new KeebLayoutModel(Keyboard.P, new MatrixPosition(2, 10), new LedPosition(5, 12, 53), new MatrixPosition(4, 10)) },
            { Keyboard.LeftBracket, new KeebLayoutModel(Keyboard.LeftBracket, new MatrixPosition(2, 11), new LedPosition(5, 13, 54), new MatrixPosition(4, 11)) },
            { Keyboard.RightBracket, new KeebLayoutModel(Keyboard.RightBracket, new MatrixPosition(2, 12), new LedPosition(5, 14, 55), new MatrixPosition(4, 12)) },
            { Keyboard.DELETE, new KeebLayoutModel(Keyboard.DELETE, new MatrixPosition(2, 14), new LedPosition(5, 17, 57), new MatrixPosition(4, 14)) },
            { Keyboard.END, new KeebLayoutModel(Keyboard.END, new MatrixPosition(2, 15), new LedPosition(5, 18, 58), new MatrixPosition(4, 15)) },
            { Keyboard.PAGEDown, new KeebLayoutModel(Keyboard.PAGEDown, new MatrixPosition(2, 16), new LedPosition(5, 19, 59), new MatrixPosition(4, 16)) },
            //Row 8
            { Keyboard.CapLock, new KeebLayoutModel(Keyboard.CapLock, new MatrixPosition(3,0), new LedPosition(6, 1 , 64), new MatrixPosition(5, 0)) },
            { Keyboard.A, new KeebLayoutModel(Keyboard.A, new MatrixPosition(3,1), new LedPosition(6, 3 , 65), new MatrixPosition(5, 1)) },
            { Keyboard.S, new KeebLayoutModel(Keyboard.S, new MatrixPosition(3,2), new LedPosition(6, 4 , 66), new MatrixPosition(5, 2)) },
            { Keyboard.D, new KeebLayoutModel(Keyboard.D, new MatrixPosition(3,3), new LedPosition(6, 5, 67), new MatrixPosition(5, 3)) },
            { Keyboard.F, new KeebLayoutModel(Keyboard.F, new MatrixPosition(3,4), new LedPosition(6, 6, 68), new MatrixPosition(5, 4)) },
            { Keyboard.G, new KeebLayoutModel(Keyboard.G, new MatrixPosition(3,5), new LedPosition(6, 7, 69), new MatrixPosition(5, 5)) },
            { Keyboard.H, new KeebLayoutModel(Keyboard.H, new MatrixPosition(3,6), new LedPosition(6, 8, 70), new MatrixPosition(5, 6)) },
            { Keyboard.J, new KeebLayoutModel(Keyboard.J, new MatrixPosition(3,7), new LedPosition(6, 9, 71), new MatrixPosition(5, 7)) },
            { Keyboard.K, new KeebLayoutModel(Keyboard.K, new MatrixPosition(3,8), new LedPosition(6, 10, 72), new MatrixPosition(5, 8)) },
            { Keyboard.L, new KeebLayoutModel(Keyboard.L, new MatrixPosition(3,9), new LedPosition(6, 11, 73), new MatrixPosition(5, 9)) },
            { Keyboard.Semicolon, new KeebLayoutModel(Keyboard.Semicolon, new MatrixPosition(3,10), new LedPosition(6, 12, 74), new MatrixPosition(5, 10)) },
            { Keyboard.SingleQuote, new KeebLayoutModel(Keyboard.SingleQuote, new MatrixPosition(3,11), new LedPosition(6, 13, 75), new MatrixPosition(5, 11)) },
            { Keyboard.Europe1, new KeebLayoutModel(Keyboard.Europe1, new MatrixPosition(3,12), new LedPosition(6, 14, 76), new MatrixPosition(5, 12)) },
            { Keyboard.Enter, new KeebLayoutModel(Keyboard.Enter, new MatrixPosition(3,13), new LedPosition(6, 15, 77), new MatrixPosition(4, 13)) },
            //Row 10
            { Keyboard.LeftShift, new KeebLayoutModel(Keyboard.LeftShift, new MatrixPosition(4, 0), new LedPosition(7, 1, 85), new MatrixPosition(6, 0)) },
            { Keyboard.Europe2, new KeebLayoutModel(Keyboard.Europe2, new MatrixPosition(4, 1), new LedPosition(7, 2, 86), new MatrixPosition(6, 1)) },
            { Keyboard.Z, new KeebLayoutModel(Keyboard.Z, new MatrixPosition(4, 2), new LedPosition(7, 3, 87), new MatrixPosition(6, 2)) },
            { Keyboard.X, new KeebLayoutModel(Keyboard.X, new MatrixPosition(4, 3), new LedPosition(7, 4, 88), new MatrixPosition(6, 3)) },
            { Keyboard.C, new KeebLayoutModel(Keyboard.C, new MatrixPosition(4, 4), new LedPosition(7, 5, 89), new MatrixPosition(6, 4)) },
            { Keyboard.V, new KeebLayoutModel(Keyboard.V, new MatrixPosition(4, 5), new LedPosition(7, 7, 90), new MatrixPosition(6, 5)) },
            { Keyboard.B, new KeebLayoutModel(Keyboard.B, new MatrixPosition(4, 6), new LedPosition(7, 8, 91), new MatrixPosition(6, 6)) },
            { Keyboard.N, new KeebLayoutModel(Keyboard.N, new MatrixPosition(4, 7), new LedPosition(7, 9, 92), new MatrixPosition(6, 7)) },
            { Keyboard.M, new KeebLayoutModel(Keyboard.M, new MatrixPosition(4, 8), new LedPosition(7, 10, 93), new MatrixPosition(6, 8)) },
            { Keyboard.Comma, new KeebLayoutModel(Keyboard.Comma, new MatrixPosition(4, 9), new LedPosition(7, 11, 94), new MatrixPosition(6, 9)) },
            { Keyboard.Period, new KeebLayoutModel(Keyboard.Period, new MatrixPosition(4, 10), new LedPosition(7, 12, 95), new MatrixPosition(6, 10)) },
            { Keyboard.Slash, new KeebLayoutModel(Keyboard.Slash, new MatrixPosition(4, 11), new LedPosition(7, 13, 96), new MatrixPosition(6, 11)) },
            { Keyboard.RightShift, new KeebLayoutModel(Keyboard.RightShift, new MatrixPosition(4, 13), new LedPosition(7, 15, 98), new MatrixPosition(6, 12)) },
            { Keyboard.UP, new KeebLayoutModel(Keyboard.UP, new MatrixPosition(4, 15), new LedPosition(7, 18, 100), new MatrixPosition(6, 13)) },
            //Row 12
            { Keyboard.CTRL_L, new KeebLayoutModel(Keyboard.CTRL_L, new MatrixPosition(5, 0), new LedPosition(8, 1, 106), new MatrixPosition(7, 0)) },
            { Keyboard.WIN_L, new KeebLayoutModel(Keyboard.WIN_L, new MatrixPosition(5, 1), new LedPosition(8, 2, 107), new MatrixPosition(7, 1)) },
            { Keyboard.ALT_L, new KeebLayoutModel(Keyboard.ALT_L, new MatrixPosition(5, 2), new LedPosition(8, 3, 108), new MatrixPosition(7, 2)) },
            { Keyboard.SPACE_LL, new KeebLayoutModel(Keyboard.SPACE_LL, null, new LedPosition(8, 5, 110), null) },
            { Keyboard.SPACE_L, new KeebLayoutModel(Keyboard.SPACE_L, null, new LedPosition(8, 6, 111), null) },
            { Keyboard.SPACE, new KeebLayoutModel(Keyboard.SPACE, new MatrixPosition(5, 6), new LedPosition(8, 7, 112), new MatrixPosition(7, 3)) },
            { Keyboard.SPACE_R, new KeebLayoutModel(Keyboard.SPACE_R, null, new LedPosition(8, 8, 113), null) },
            { Keyboard.SPACE_RR, new KeebLayoutModel(Keyboard.SPACE_RR, null, new LedPosition(8, 9, 114), null) },
            { Keyboard.ALT_R, new KeebLayoutModel(Keyboard.ALT_R, new MatrixPosition(5, 10), new LedPosition(8, 12, 116), new MatrixPosition(7, 4)) },
            { Keyboard.FN, new KeebLayoutModel(Keyboard.FN, new MatrixPosition(5, 11), new LedPosition(8, 13, 117), new MatrixPosition(7, 5)) },
            { Keyboard.Menu, new KeebLayoutModel(Keyboard.Menu, new MatrixPosition(5, 12), new LedPosition(8, 14, 118), new MatrixPosition(7, 6)) },
            { Keyboard.CTRL_R, new KeebLayoutModel(Keyboard.CTRL_R, new MatrixPosition(5, 13), new LedPosition(8, 15, 119), new MatrixPosition(7, 7)) },
            { Keyboard.LEFT, new KeebLayoutModel(Keyboard.LEFT, new MatrixPosition(5, 14), new LedPosition(8, 17, 120), new MatrixPosition(7, 8)) },
            { Keyboard.DOWN, new KeebLayoutModel(Keyboard.DOWN, new MatrixPosition(5, 15), new LedPosition(8, 18, 121), new MatrixPosition(7, 9)) },
            { Keyboard.RIGHT, new KeebLayoutModel(Keyboard.RIGHT, new MatrixPosition(5, 16), new LedPosition(8, 19, 122), new MatrixPosition(7, 10)) },
        };

        public static List<Keyboard> ISOButtonPusherKeys =>
        [
            //Keyboard.ESC, Keyboard.F1, Keyboard.F2, Keyboard.F3, Keyboard.F4, Keyboard.F5, Keyboard.F6, Keyboard.F7, Keyboard.F8, Keyboard.F9, Keyboard.F10, Keyboard.F11, Keyboard.F12,
            Keyboard.Tilde, Keyboard.One, Keyboard.Two, Keyboard.Three, Keyboard.Four, Keyboard.Five, Keyboard.Six, Keyboard.Seven, Keyboard.Eight, Keyboard.Nine, Keyboard.Zero, Keyboard.Hyphen, Keyboard.Plus, Keyboard.BackSpace,
            Keyboard.Tab, Keyboard.Q, Keyboard.W, Keyboard.E, Keyboard.R, Keyboard.T, Keyboard.Y, Keyboard.U, Keyboard.I, Keyboard.O, Keyboard.P, Keyboard.LeftBracket, Keyboard.RightBracket,
            Keyboard.CapLock, Keyboard.A, Keyboard.S, Keyboard.D, Keyboard.F, Keyboard.G, Keyboard.H, Keyboard.J, Keyboard.K, Keyboard.L, Keyboard.Semicolon, Keyboard.SingleQuote, Keyboard.Europe1, Keyboard.Enter,
            Keyboard.LeftShift, Keyboard.Europe2, Keyboard.Z, Keyboard.X, Keyboard.C, Keyboard.V, Keyboard.B, Keyboard.N, Keyboard.M, Keyboard.Comma, Keyboard.Period, Keyboard.Slash, Keyboard.RightShift,
            //Keyboard.CTRL_L, Keyboard.WIN_L, Keyboard.ALT_L, Keyboard.ALT_R, Keyboard.FN, Keyboard.MOUSE, Keyboard.CTRL_R,
            Keyboard.SPACE,
            //Keyboard.PrnSrc, Keyboard.ScrLk, Keyboard.Pause, Keyboard.Insert, Keyboard.NumLock, Keyboard.NumBackSlash, Keyboard.NUM_Multiple, Keyboard.NUM_Hypen,
            //Keyboard.NUM_1, Keyboard.NUM_2, Keyboard.NUM_3, Keyboard.NUM_4, Keyboard.NUM_5, Keyboard.NUM_6, Keyboard.NUM_7, Keyboard.NUM_8, Keyboard.NUM_9, Keyboard.NUM_0, Keyboard.NUM_Plus, Keyboard.NUM_DEL, Keyboard.NUM_Enter,
            //Keyboard.DELETE, Keyboard.HOME, Keyboard.PAGEUp, Keyboard.PAGEDown, Keyboard.UP, Keyboard.DOWN, Keyboard.LEFT, Keyboard.RIGHT, Keyboard.DEL, Keyboard.END,
        ];
        #endregion

        public static List<Keyboard> SPACE_BAR_KEYS => [Keyboard.SPACE_LL, Keyboard.SPACE_L, Keyboard.SPACE, Keyboard.SPACE_R, Keyboard.SPACE_RR];
    }
}
